### PR TITLE
Add remko to AUTHORS.rst

### PR DESCRIPTION
**Pull request by remko**
Per https://github.com/svaarala/duktape-wiki/pull/139

### CODE REVIEW

**Comment by svaarala** [comment]
You should actually be on the first author list which is for code and documentation.

**Comment by remko** [comment]
Updated the PR. Could it be that the CI bot doesn't like me rewriting the commit?

**Comment by svaarala** [comment]
Hmm, do you have an up-to-date Duktape master? If not that might explain the GH-indicated conflict.

**Comment by remko** [comment]
Sorry about that, my copy was indeed out of date. I was convinced I hadn't cloned the repo before when I cloned this morning, so I assumed I was working on an up-to-date copy.

**Comment by svaarala** [comment]
No worries, looks good now, thanks :)

**Pull request merged**
