### PR TITLE
Add linenoise hints to 'duk'

### PR DESCRIPTION
**Pull request by svaarala**
- [x] Convert completion handling to a script
- [x] Add hints handling as a script

### CODE REVIEW

**Comment by svaarala** [comment]
Example of hints:

hints

**Comment by svaarala** [comment]
Encountered #1079 in writing the linenoise scripts.

**Comment by fatcerberus** [comment]
Those hints look nifty.  Chrome's JS console has something like that which makes it a joy to use compared to the Node.js REPL.

**Comment by svaarala** [comment]
It's still a bit barebones and only recognizes a maximal sequence like `foo.bar.qu` at the end of the input. But for example `[].leng` won't provide a hint or completion with TAB.

But now that the completion/hint code is scripted it's easier to experiment with it and improve it. Errors are cleanly caught and won't be segfaults.

**Comment by svaarala** [comment]
@fatcerberus Linenoise doesn't support Windows but linenoise-ng does and is intended to be API compatible if I understood correctly. I'll try that out if I have time later tonight.

**Pull request merged**
