### PR TITLE
Add support for ToNumber() octal and binary conversion

### PR DESCRIPTION
**Pull request by svaarala**
See https://github.com/svaarala/duktape/pull/1028#issuecomment-260497240.

- [x] Change ToNumber() to support ES6 octal and binary (still no legacy octal)
- [x] Testcase coverage
- [x] Releases entry

### CODE REVIEW

**Comment by fatcerberus** [comment]
Also according to ES6, binary, e.g. ToNumber("0b1101") = 13.

**Comment by svaarala** [comment]
Yep, legacy octal is still not recognized (matches V8):

```
> +'01234'
1234
> +'0o1234'
668
> +'0b10001'
17
```

Current Duktape:

```
duk> +'01234'
= 1234
duk> +'0o1234'
= NaN
duk> +'0b10001'
= NaN
```

**Comment by fatcerberus** [comment]
Wait, shouldn't the latter two coerce to zero in Duktape, or does having garbage anywhere in the string automatically = NaN?

**Comment by svaarala** [comment]
Garbage is a NaN yes. That's also noted in Annex E:

> [...] In previous editions such strings were converted to NaN [...]

That's different from parseInt() which stops parsing at garbage but allows the pre-garbage part to be parsed:

```
> parseInt('123foo')
123
```

Here's a related fun table :-): https://github.com/svaarala/duktape/blob/master/doc/number-conversion.rst#lexical-trivia-differences-in-call-sites

**Comment by fatcerberus** [comment]
I notice in that table that `parseInt()` has special handling for hex "0xNNN".  Is this the case in ES6 for octal and binary too?  If so that might be good to fix in this pull also.

**Comment by svaarala** [comment]
I don't think parseInt() supports octal or binary; from Node.js:

```
> parseInt('0x123')
291
> parseInt('0o123')
0
> parseInt('0b10001')
0
```

Duktape master:

```
duk> parseInt('0x123')
= 291
duk> parseInt('0o123')
= 0
duk> parseInt('0b10001')
= 0
```

So parseInt() seems fine.

**Comment by svaarala** [comment]
Ok, now works as expected:

```
((o) Duktape [linenoise] 1.99.99 (v1.5.0-941-g3b5721a-dirty)
duk> +'01234'
= 1234
duk> +'0o1234'
= 668
duk> +'0b10001'
= 17
```

**Pull request merged**
