### PR TITLE
Update AUTHORS.rst

### PR DESCRIPTION
**Pull request by v00d00**
As per https://github.com/svaarala/duktape-wiki/pull/216#issuecomment-487740848

### CODE REVIEW

**Comment by svaarala** [comment]
You should actually be on the first list (= actual repo contributions). I think I accidentally said you should be on the second (= bug reports and such without repo contributions). Could you fix and squash?

**Comment by svaarala** [comment]
Hi, just wanted to remind that you should be on the first list (not the second).

**Comment by v00d00** [comment]
Sorry, changed and rebased!

**Comment by svaarala** [comment]
Thanks!

**Pull request merged**
