### PR TITLE
Makefile.sharedlibrary: support macOS

### PR DESCRIPTION
**Pull request by apjanke**
What do you think about modifying `Makefile.sharedlibrary` to support macOS out of the box?

(I have only tested this PR on Mac; I don't have a Linux or Windows box handy for testing.)

### CODE REVIEW

**Comment by svaarala** [comment]
The main problem is that after adding a few platform one reaches a point where it's no longer easy to add further platforms. That's why the project policy so far has been that there are no official build files for different platforms (not even all different Linux variants).

That said, as long as someone is willing to maintain the changes, I have no objection to the changes. And it's certainly nice if the repo would work with (mainline) Linux, macOS, and Windows out of the box.

**Comment by apjanke** [comment]
Hmm. That's a judgment call for you to make. I understand the concern.

I would be willing to maintain the macOS parts of this Makefile. (Though I can't do much to support the main Duktape code on Mac.)

**Comment by svaarala** [comment]
> I would be willing to maintain the macOS parts of this Makefile. (Though I can't do much to support the main Duktape code on Mac.)

That's good enough for me, there's relatively little macOS-specific work in the main code base because it depends so little on the target.

**Comment by apjanke** [comment]
Excellent.

**Comment by svaarala** [comment]
I don't think Makefile.sharedlibrary has support Windows in the past so I guess testing Linux + macOS should be fine. I can test the Linux part later on when I get a chance.

**Comment by svaarala** [comment]
@apjanke Took a little time to get back to this, but seems to work on Linux so merging :)

**Comment by apjanke** [comment]
Thanks!

**Pull request merged**
