### PR TITLE
Remove /tmp assumption from runtests.js

### PR DESCRIPTION
**Pull request by svaarala**
- [x] Use 'tmp' package for auto-deleting temporary filenames.  This should be portable to e.g. Windows, and obeys `TMP` on Unix which is preferable.
- [x] Figure out Python error on Windows => skipped

### CODE REVIEW

**Comment by svaarala** [comment]
@fatcerberus If you have a chance to try to see if this allows you to run `qecmatest` that'd be useful :)

I'll try this on my Windows setup before merging but it'll take a bit.

**Comment by fatcerberus** [comment]
I can try it in a couple hours.

**Comment by fatcerberus** [comment]
After editing the makefile to quote `"$(NODE)"` (because the Windows installer put Node.js in Program Files, seriously, what moron at MS had the bright idea to put spaces in the default directory for *programs*?), I get the following error with clean install of node:
```
### qecmatest
"/cygdrive/c/Program Files/nodejs/node" runtests/runtests.js --prep-test-path util/prep_test.py --minify-uglifyjs2 UglifyJS2/bin/uglifyjs --util-include-path tests/ecmascript --known-issues doc/testcase-known-issues.yaml --run-duk --cmd-duk=/cygdrive/d/src/duktape/duk --num-threads 16 --log-file=/tmp/duk-test.log tests/ecmascript/
module.js:338
    throw err;
    ^

Error: Cannot find module 'tmp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\src\duktape\runtests\runtests.js:11:11)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
Makefile:511: recipe for target 'qecmatest' failed
make: *** [qecmatest] Error 1
```

Do I need to use `npm` to install something else first?

**Comment by svaarala** [comment]
Yeah, you need `npm install`, there's a new dependency.

**Comment by svaarala** [comment]
Alternatively you could just delete the `node_modules` and allow the dependency to reinstall them.

**Comment by svaarala** [comment]
To clarify, those need to be done in the `runtests/` directory, so either: (1) `cd runtests; npm install` or (2) `cd runtests; rm -rf node_modules`.

**Comment by svaarala** [comment]
The makefile also uses a `/tmp/` path for the log file output so that'll fail at the end.

**Comment by fatcerberus** [comment]
Okay, I got a bit further this time, now I get a string of these:
```
  cmd: 'python util/prep_test.py --minify-uglifyjs2 UglifyJS2/bin/uglifyjs --util-include-path tests/ecmascript --input tests\\ecmascript\\util-nodejs-buffer.js --output C:\\cygwin64\\tmp\\tmp-runtests-3124f024ZXWbPCRi --prologue C:\\cygwin64\\tmp\\tmp-runtests-3124bfjs3u4boFxf' }
{ [Error: spawn python ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn python',
  path: 'python',
  spawnargs:
   [ 'util/prep_test.py',
     '--minify-uglifyjs2',
     'UglifyJS2/bin/uglifyjs',
     '--util-include-path',
     'tests/ecmascript',
     '--input',
     'tests\\ecmascript\\util-typedarray.js',
     '--output',
     'C:\\cygwin64\\tmp\\tmp-runtests-3124V5owHkPS7SEe',
     '--prologue',
     'C:\\cygwin64\\tmp\\tmp-runtests-3124m36lBc3CiQYc' ],
```

My first guess was that Cygwin Python doesn't like the Windows paths, but that doesn't seem to be it: `cd C:\\cygwin64\\tmp` works correctly under bash and `ls` shows all the "tmp-runtests-xxxx" files (so they were created successfully).  So yeah, no idea what's wrong here.

**Comment by fatcerberus** [comment]
Odd... I ran `cat *` in `tmp/` and saw all output from the tests, so the tests did run.  Which makes the Python spawn errors above even more perplexing.

**Comment by svaarala** [comment]
I can hold off merging this branch until we figure out what's still going wrong - or I can merge this and we can work on the rest separately. Your call :)

I am migrating to a new test runner towards the end of the year, so maybe this doesn't matter all that much. That is going to be client-server based and allow test clients on multiple platforms to participate in a test run, which should help compiler/platform coverage quite a lot.

**Comment by fatcerberus** [comment]
Hm, I see no reason why it should be failing, I'm running this under Cygwin so that should provide a fully transparent Unix build environment.  So unless you have any insights into what's wrong I say just merge this as-is.

**Comment by svaarala** [comment]
One thing that's certainly broken is the Makefile's use of /tmp/ files directly. Perhaps the files should just be in the current directory with clean targets for them. Messy :P

**Comment by fatcerberus** [comment]
The mention of makefiles reminds me, I found another use for Duktape recently: An scons-inspired game compiler/packager which will be provided as a companion to minisphere in v2.0.

**Pull request merged**
