### PR TITLE
Add duk_ret_t return value to duk_{throw,error,error_va,fatal}() prototype

### PR DESCRIPTION
**Pull request by svaarala**
While the functions never return, a `duk_ret_t` return value allows application code to do something like:

```c
if (argvalue < 0) {
    return duk_error(ctx, DUK_ERR_TYPE_ERROR, "invalid arg: %d", (int) argvalue);
}
```

If this is not the case and the compiler doesn't support noreturn functions, application code needs an explicit return after a `duk_error()` to prevent potential compiler warnings (e.g. use of uninitialized variables) when the compiler thinks execution will resume after the error.

Same treatment for `duk_error_va()`, `duk_throw()`, and `duk_fatal()`.

Tasks:
- [x] API changes
- [x] Testcases
- [x] API documentation changes
- [x] 2.x migration note (just a note there's a return value now)
- [x] Releases entry

### CODE REVIEW

**Comment by svaarala** [comment]
There's one more convenience issue in this idiom:

```c
if (argvalue < 0) {
    return duk_error(ctx, DUK_ERR_TYPE_ERROR, "invalid arg: %d", (int) argvalue);
}
```

The error type argument is a bit awkward, so I'll add a few type specific calls in a separate pull so that one can:

```c
if (argvalue < 0) {
    return duk_type_error(ctx, "invalid arg: %d", (int) argvalue);
}
```

After this change the error functions are a bit nicer to use.

**Comment by fatcerberus** [comment]
Hm, MSVC is apparently not a big fan of this change:
```
1>..\src\shared\duktape.c(19863): warning C4646: function declared with 'noreturn' has non-void return type
1>..\src\shared\duktape.c(19905): warning C4646: function declared with 'noreturn' has non-void return type
1>..\src\shared\duktape.c(19934): warning C4646: function declared with 'noreturn' has non-void return type
1>..\src\shared\duktape.c(19944): warning C4646: function declared with 'noreturn' has non-void return type
```

**Comment by svaarala** [comment]
That would be easy to fix by removing the noreturn. But without noreturn the generated call sites are much worse (and larger).

I could change the calls to be macros like:

```c
#define duk_error(ctx,err_code,...) \
    (duk_error_raw(<args>), 0) 
```

and then change `duk_error_raw()` back to returning void.

That would run the risk of creating warnings for "unreachable code" but it's worth a try.

**Comment by fatcerberus** [comment]
I don't think that works.  The comma operator requires a value in all positions, a void-returning function isn't valid in that context I think...?

**Pull request merged**
