### PR TITLE
Debugger pause trivia

### PR DESCRIPTION
**Pull request by svaarala**
- Minor documentation edits

### CODE REVIEW

**Comment by svaarala** [comment]
@fatcerberus Just a few edits I didn't want to bother you with - the main thing being to clarify that (1) the call returns immediately (which may not be apparent) and (2) that it's safe to call and a no-op when already paused.

**Comment by fatcerberus** [comment]
Looks good.  It was difficult to get the API documentation right - I wanted to communicate as much of the semantics as possible without making the summary overly long.  Your rewrite did a good job I think. :)

**Comment by svaarala** [comment]
I tried rewording the pause description a bit more; I removed some of the overlap from the debugger.rst (it doesn't need to be as detailed as the API documentation).

**Comment by fatcerberus** [comment]
Looks much better now. :)

**Pull request merged**
