### PR TITLE
Add duk_is_buffer_data() API call

### PR DESCRIPTION
**Pull request by svaarala**
Add `duk_is_buffer_data()` API call for reliably checking whether a value stack entry is a plain buffer or any of the buffer types, in other words: "value stack entry has data". Before this addition one could use `duk_get_buffer_data() != NULL` but there are corner cases with zero-size buffers where that method doesn't work.

- [x] Add API call
- [x] Testcase coverage
- [x] Test -UDUK_USE_BUFFEROBJECT_SUPPORT manually
- [x] API docs
- [x] Releases entry

### CODE REVIEW

**Comment by fatcerberus** [comment]
I wonder if the API shouldn't be called `duk_has_buffer_data()` instead...

**Comment by svaarala** [comment]
That was my instinct as well - but it would then be inconsistent with existing type check functions. It's a grey area because while it's checking for specific types in practice (plain buffer or any buffer object) the programmer intent is closer to "does this value have a read/write data buffer?". Those two questions are now 1:1.

**Comment by svaarala** [comment]
One option was something like `duk_is_buffer_like()` to signify it's checking for a range of different buffer types (and "like" because views are not actually buffers if you follow ES terminology).

**Comment by fatcerberus** [comment]
Ecmascript also has a concept of ArrayBuffer "neutering".  I don't think Duktape supports that now, but assuming it did at some point in the future, would we want this API to return false then?  If so then it would no longer be strictly a type check.

**Comment by svaarala** [comment]
Duktape handles neutering (plain buffer reference is NULL) in a very rough manner so the data structure is there already. But there's no API to actually neuter buffers (Khronos doesn't provide it for example) yet.

But I think a neutered buffer should probably work similarly to an "uncovered" buffer where the apparent size is larger than the backing buffer. The safe thing is to say that data pointer is NULL and size is 0, but recognize it as a buffer.

The other option of considering a non-buffer for type checking would also be reasonable though.

**Pull request merged**
