### PR TITLE
Add Windows debug transport example

### PR DESCRIPTION
**Pull request by svaarala**
Add a Windows variant of the debug transport example and ensure `duk --debugger` works on Windows.

Tasks:

- [x] Add Windows debug transport example
- [x] Update internal and external documentation
- [x] Debugger Makefile trivia for Windows (still Cygwin but support e.g. spaces in Node.js path)
- [x] Test on Windows with Linux debug client
- [x] Test on Windows with Windows debug client
- [x] Releases entry

### CODE REVIEW

**Comment by svaarala** [comment]
Work in progress still, I'll try to get this working today.

**Comment by svaarala** [comment]
Ok, this works for me at least on MSVC 2013.

Tried both a Windows and a Linux debug client.

**Comment by svaarala** [comment]
Any comments on Windows best practices from more experienced Windows programmers welcome :-)

**Comment by fatcerberus** [comment]
I assume you mean in general?

One thing to watch out for is paths - Windows itself will happily parse paths using `/` separators, however the default shell (cmd.exe) will sometimes misinterpret them as command options.  If you're invoking the shell for any reason, better use backslashes.

**Comment by svaarala** [comment]
I mean if the `duk_trans_socket_windows.c` socket code is doing something contrary to best WIndows practices.

**Comment by fatcerberus** [comment]
I don't think it's necessary to check whether _WIN32_LEAN_AND_MEAN is defined before defining it: as far as I'm aware, in no case will MSVC define it by default.

The socket code looks good.  Winsock isn't all that different from UNIX/BSD sockets, so nothing much to go wrong there.  The only thing I notice is that you're using AF_INET, which implies IPv4 and will fail on IPv6-only systems.  Probably not an issue in practice though, and it's just example code anyway.

The one thing that legitimately bugs me is this:
 ```c
#pragma comment (lib, "Ws2_32.lib")
```

That probably won't work with any compiler other than MSVC.  MinGW uses UNIX-style library names, for example (libfoo.a)

**Comment by svaarala** [comment]
Both the _WIN32_LEAN_AND_MEAN (though not checking before defining it, that was from some other example) and the pragma are from this example: https://msdn.microsoft.com/en-us/library/windows/desktop/ms737593(v=vs.85).aspx

Should AF_INET be AF_UNSPEC instead?

I'll place that pragma inside a `#if defined(_MSC_VER)`.

**Comment by fatcerberus** [comment]
AF_UNSPEC is probably the best choice.  Beware that, if the hostname is NULL, it will sometimes prefer IPv6 if both protocols are available (speaking from experience :) ) But this can easily be overridden by using a "catch-all" hostname for the desired protocol (`0.0.0.0` or `::`)

**Comment by svaarala** [comment]
Hmm, so would you suggest using "0.0.0.0" and AF_UNSPEC?

**Comment by svaarala** [comment]
Minor fixes here (I'll squash this later): https://github.com/svaarala/duktape/commit/15704aef53e91b4474429fba0f2d9cecddaecc1e

**Comment by svaarala** [comment]
To clarify, would you suggest the default to be "0.0.0.0" and AF_UNSPEC, and the user can then override DUK_DEBUG_ADDRESS to something else if necessary?

**Comment by fatcerberus** [comment]
Just for the record, I think that would have the same outcome as AF_INET if the system has no IPv4 support.  The only way to support v4 and v6 simultaneously is to open two listening sockets.

For this example code dual sockets is probably complicating things too much.  The DUK_DEBUG_ADDRESS with a default hostname is a good compromise. :)

**Comment by svaarala** [comment]
Ok, I'll leave that in and retest, rebase, and merge unless something comes up. Thanks! :)

**Comment by fatcerberus** [comment]
The reason for the above is that Windows implements IPv4 and IPv6 as completely separate networking stacks.  I don't think this is the case in, e.g. Linux.

**Comment by svaarala** [comment]
Right, AF_UNSPEC is then maybe preferable because one can then just `-DDUK_DEBUG_ADDRESS=xxx` to make the transport bind to IPv6. If AF_INET was in place you'd need to tweak the source.

Quite a minor detail of course.

**Comment by svaarala** [comment]
Ok, things still seem to work fine with VS2013.

**Comment by svaarala** [comment]
For MinGW needed to apply this workaround to get around "missing getaddrinfo()" during linking: http://programmingrants.blogspot.fi/2009/09/tips-on-undefined-reference-to.html

**Comment by svaarala** [comment]
Ok, with the fix both VS2013 and MinGW work correctly. Also added example command lines into the source comment to illustrate correct MinGW link options. I'll merge once the tests pass.

**Pull request merged**
