### PR TITLE
Post-release cleanups after 1.4.0 release

### PR DESCRIPTION
**Pull request by svaarala**

### CODE REVIEW

**Comment by fatcerberus** [comment]
Nice, the performance improvements in 1.4 are worth the upgrade alone

**Comment by fatcerberus** [comment]
Not to mention my debugger enhancements. :)

**Comment by JoshEngebretson** [comment]
I haven't had any time to check our Emscripten performance on Duktape 1.4 in depth, though eyeballing it is *definitely* smoother, need some better performance metrics from here! :)

**Comment by svaarala** [comment]
@JoshEngebretson I think the next step for Emscripten performance would be to figure out how well the executor switch-case structure compiles and performs, as that seemed to be slower (relatively speaking) than other native code such as array algorithms etc.

**Comment by svaarala** [comment]
@fatcerberus Yeah, thanks for all that debugger work :)

**Pull request merged**
