### PR TITLE
Rewrite the string table data structure

### PR DESCRIPTION
**Pull request by svaarala**
Replace the two alternative algorithms with a single one which works for both desktop and low memory cases.

The string table algorithm has footprint impact and performance impact when running code that creates a lot of string values on the fly. Code that uses fixed string keys, local variables, call functions etc, is not affected by the string table algorithm much because after interning the strings are just passed around by reference. The main motivation in the pull is to settle on a single algorithm without impacting footprint too much. Performance improvements are also possible, but not the main focus.

Revised approachis to make strings single linked and use a simple chaining array for them.

Tasks:
- [x] Prototype a few approaches
- [x] Grow/shrink support; inline realloc when possible
- [x] Pointer compression support
- [x] ROM string handling, esp. link pointers
- [x] Footprint optimize algorithms
- [x] Downgrade logging
- [x] Internal document for revised design
- [x] Config option changes
- [x] Internal documentation changes
- [x] Releases entry
- [x] Final code review, especially side effect handling
- [x] Perf test run

Follow-ups:
- Make the checked allocation case the default?
- Use ROM pointer link field for string data (affects DUK_HSTRING_GET_DATA)?
- Because heap->st_size == heap->st_mask + 1 at all times, tracking only heap->st_mask is enough
- Better statistics gathering

### CODE REVIEW

**Comment by svaarala** [comment]
Double linked list testing:

```
test-add-fastint.js                 : duk.O2  0.74 duk.O2.master  0.73
test-add-float.js                   : duk.O2  0.75 duk.O2.master  0.78
test-add-nan-fastint.js             : duk.O2  0.83 duk.O2.master  0.89
test-add-nan.js                     : duk.O2  0.74 duk.O2.master  0.75
test-arith-add.js                   : duk.O2  3.14 duk.O2.master  2.93
test-arith-div.js                   : duk.O2  8.06 duk.O2.master  8.07
test-arith-mod.js                   : duk.O2  7.14 duk.O2.master  7.10
test-arith-mul.js                   : duk.O2  4.11 duk.O2.master  4.41
test-arith-sub.js                   : duk.O2  2.91 duk.O2.master  3.08
test-array-append.js                : duk.O2  0.57 duk.O2.master  0.57
test-array-cons-list.js             : duk.O2  0.94 duk.O2.master  0.96
test-array-foreach.js               : duk.O2  3.02 duk.O2.master  2.99
test-array-literal.js               : duk.O2  1.82 duk.O2.master  1.76
test-array-pop.js                   : duk.O2  2.50 duk.O2.master  2.45
test-array-push.js                  : duk.O2  2.70 duk.O2.master  2.72
test-array-read-lenloop.js          : duk.O2  2.17 duk.O2.master  2.10
test-array-read.js                  : duk.O2  1.96 duk.O2.master  1.94
test-array-sort.js                  : duk.O2  3.72 duk.O2.master  3.77
test-array-write-length.js          : duk.O2  1.67 duk.O2.master  1.78
test-array-write.js                 : duk.O2  1.91 duk.O2.master  2.00
test-assign-add.js                  : duk.O2  4.07 duk.O2.master  4.05
test-assign-addto-nan.js            : duk.O2  1.32 duk.O2.master  1.41
test-assign-addto.js                : duk.O2  4.04 duk.O2.master  4.02
test-assign-boolean.js              : duk.O2  4.75 duk.O2.master  4.76
test-assign-const-int.js            : duk.O2  2.62 duk.O2.master  2.77
test-assign-const-int2.js           : duk.O2  5.13 duk.O2.master  6.38
test-assign-const.js                : duk.O2  4.26 duk.O2.master  4.42
test-assign-literal.js              : duk.O2  4.17 duk.O2.master  4.26
test-assign-proplhs-reg.js          : duk.O2  2.99 duk.O2.master  2.90
test-assign-proprhs.js              : duk.O2  3.32 duk.O2.master  3.05
test-assign-reg.js                  : duk.O2  3.08 duk.O2.master  3.02
test-base64-decode-whitespace.js    : duk.O2  1.98 duk.O2.master  2.02
test-base64-decode.js               : duk.O2  1.64 duk.O2.master  1.62
test-base64-encode.js               : duk.O2  1.84 duk.O2.master  1.85
test-bitwise-ops.js                 : duk.O2  2.10 duk.O2.master  2.01
test-break-fast.js                  : duk.O2  1.49 duk.O2.master  1.53
test-break-slow.js                  : duk.O2  8.25 duk.O2.master  8.42
test-buffer-nodejs-read.js          : duk.O2  2.43 duk.O2.master  2.50
test-buffer-nodejs-write.js         : duk.O2  3.24 duk.O2.master  3.28
test-buffer-object-read.js          : duk.O2  2.51 duk.O2.master  2.53
test-buffer-object-write.js         : duk.O2  3.35 duk.O2.master  3.32
test-buffer-plain-read.js           : duk.O2  2.01 duk.O2.master  2.06
test-buffer-plain-write.js          : duk.O2  2.00 duk.O2.master  2.01
test-call-basic-1.js                : duk.O2  8.89 duk.O2.master  8.50
test-call-basic-2.js                : duk.O2  8.60 duk.O2.master  8.47
test-call-basic-3.js                : duk.O2 10.92 duk.O2.master 10.48
test-call-basic-4.js                : duk.O2 19.54 duk.O2.master 18.94
test-call-native.js                 : duk.O2 14.77 duk.O2.master 14.64
test-call-prop.js                   : duk.O2  4.67 duk.O2.master  4.69
test-call-reg-new.js                : duk.O2  7.10 duk.O2.master  7.06
test-call-reg.js                    : duk.O2  3.31 duk.O2.master  3.33
test-call-var.js                    : duk.O2  8.32 duk.O2.master  8.51
test-compile-mandel-nofrac.js       : duk.O2 11.61 duk.O2.master 12.02
test-compile-mandel.js              : duk.O2 15.22 duk.O2.master 15.49
test-compile-short.js               : duk.O2  7.19 duk.O2.master  7.47
test-compile-string-ascii.js        : duk.O2  7.53 duk.O2.master  7.52
test-continue-fast.js               : duk.O2  1.84 duk.O2.master  1.95
test-continue-slow.js               : duk.O2  8.63 duk.O2.master  8.55
test-empty-loop-slowpath.js         : duk.O2  1.63 duk.O2.master  1.84
test-empty-loop.js                  : duk.O2  1.72 duk.O2.master  1.83
test-enum-basic.js                  : duk.O2  4.33 duk.O2.master  4.35
test-equals-fastint.js              : duk.O2  0.58 duk.O2.master  0.60
test-equals-nonfastint.js           : duk.O2  0.63 duk.O2.master  0.66
test-error-create.js                : duk.O2  2.23 duk.O2.master  2.30
test-fib.js                         : duk.O2  7.22 duk.O2.master  7.42
test-global-lookup.js               : duk.O2  8.54 duk.O2.master  8.94
test-hello-world.js                 : duk.O2  0.00 duk.O2.master  0.00
test-hex-decode.js                  : duk.O2  3.88 duk.O2.master  3.92
test-hex-encode.js                  : duk.O2  2.99 duk.O2.master  3.03
test-jc-serialize-indented.js       : duk.O2  3.80 duk.O2.master  3.74
test-jc-serialize.js                : duk.O2  2.39 duk.O2.master  2.45
test-json-parse-hex.js              : duk.O2  3.37 duk.O2.master  3.38
test-json-parse-integer.js          : duk.O2  3.36 duk.O2.master  4.14
test-json-parse-number.js           : duk.O2  5.53 duk.O2.master  5.62
test-json-parse-string.js           : duk.O2  5.06 duk.O2.master  6.07
test-json-serialize-fastpath-loop.js: duk.O2  4.02 duk.O2.master  3.94
test-json-serialize-forceslow.js    : duk.O2 10.27 duk.O2.master 10.06
test-json-serialize-hex.js          : duk.O2  1.50 duk.O2.master  1.52
test-json-serialize-indented-deep100.js: duk.O2  1.94 duk.O2.master  1.91
test-json-serialize-indented-deep25.js: duk.O2  3.57 duk.O2.master  3.57
test-json-serialize-indented-deep500.js: duk.O2  1.18 duk.O2.master  1.25
test-json-serialize-indented.js     : duk.O2  6.52 duk.O2.master  6.41
test-json-serialize-jsonrpc-message.js: duk.O2  2.06 duk.O2.master  2.09
test-json-serialize-nofrac.js       : duk.O2  0.63 duk.O2.master  0.65
test-json-serialize-plainbuf.js     : duk.O2  2.72 duk.O2.master  2.69
test-json-serialize-slowpath-loop.js: duk.O2  4.66 duk.O2.master  4.72
test-json-serialize.js              : duk.O2  6.81 duk.O2.master  6.49
test-json-string-bench.js           : duk.O2  3.75 duk.O2.master  3.83
test-json-string-stringify.js       : duk.O2  5.47 duk.O2.master  5.30
test-jx-serialize-bufobj-forceslow.js: duk.O2  4.83 duk.O2.master  5.24
test-jx-serialize-bufobj.js         : duk.O2  1.69 duk.O2.master  1.69
test-jx-serialize-indented.js       : duk.O2  3.66 duk.O2.master  3.65
test-jx-serialize.js                : duk.O2  2.33 duk.O2.master  2.45
test-mandel.js                      : duk.O2  3.13 duk.O2.master  3.31
test-object-garbage-2.js            : duk.O2  5.19 duk.O2.master  5.16
test-object-garbage.js              : duk.O2  4.73 duk.O2.master  4.84
test-object-literal.js              : duk.O2  2.99 duk.O2.master  2.90
test-prop-read-4.js                 : duk.O2  3.63 duk.O2.master  3.50
test-prop-read-8.js                 : duk.O2  3.83 duk.O2.master  3.74
test-prop-read.js                   : duk.O2  3.72 duk.O2.master  3.51
test-prop-write-1024.js             : duk.O2  3.47 duk.O2.master  3.70
test-prop-write-16.js               : duk.O2  3.67 duk.O2.master  3.87
test-prop-write-256.js              : duk.O2  4.04 duk.O2.master  4.18
test-prop-write-32.js               : duk.O2  3.62 duk.O2.master  3.47
test-prop-write-4.js                : duk.O2  3.05 duk.O2.master  3.14
test-prop-write-48.js               : duk.O2  3.75 duk.O2.master  5.56
test-prop-write-64.js               : duk.O2  4.09 duk.O2.master  3.82
test-prop-write-8.js                : duk.O2  3.31 duk.O2.master  3.36
test-prop-write.js                  : duk.O2  3.13 duk.O2.master  3.26
test-random.js                      : duk.O2  2.50 duk.O2.master  2.45
test-reg-readwrite-object.js        : duk.O2  3.33 duk.O2.master  3.22
test-reg-readwrite-plain.js         : duk.O2  2.12 duk.O2.master  2.13
test-regexp-case-insensitive.js     : duk.O2 27.34 duk.O2.master 27.08
test-regexp-compile.js              : duk.O2  2.17 duk.O2.master  2.25
test-regexp-execute.js              : duk.O2  1.50 duk.O2.master  1.59
test-regexp-string-parse.js         : duk.O2  6.33 duk.O2.master  6.72
test-strict-equals-fastint.js       : duk.O2  0.56 duk.O2.master  0.58
test-strict-equals-nonfastint.js    : duk.O2  0.60 duk.O2.master  0.62
test-string-array-concat.js         : duk.O2  5.74 duk.O2.master  5.88
test-string-arridx.js               : duk.O2  1.74 duk.O2.master  1.83
test-string-charlen-ascii.js        : duk.O2  1.10 duk.O2.master  1.11
test-string-charlen-nonascii.js     : duk.O2  2.67 duk.O2.master  2.66
test-string-compare.js              : duk.O2  2.09 duk.O2.master  2.21
test-string-decodeuri.js            : duk.O2  3.66 duk.O2.master  4.10
test-string-encodeuri.js            : duk.O2  4.35 duk.O2.master  4.40
test-string-garbage.js              : duk.O2  4.41 duk.O2.master  4.97
test-string-intern-grow-short.js    : duk.O2  3.95 duk.O2.master 11.64
test-string-intern-grow-short2.js   : duk.O2  3.82 duk.O2.master  4.68
test-string-intern-grow.js          : duk.O2  4.94 duk.O2.master 19.08
test-string-intern-grow2.js         : duk.O2  1.51 duk.O2.master  1.74
test-string-intern-match-short.js   : duk.O2  2.10 duk.O2.master  2.64
test-string-intern-match.js         : duk.O2  0.26 duk.O2.master  0.22
test-string-intern-miss-short.js    : duk.O2  2.43 duk.O2.master  3.21
test-string-intern-miss.js          : duk.O2  1.19 duk.O2.master  1.22
test-string-plain-concat.js         : duk.O2  0.89 duk.O2.master  0.86
test-string-uppercase.js            : duk.O2  2.42 duk.O2.master  2.43
test-textdecoder-ascii.js           : duk.O2  2.81 duk.O2.master  2.59
test-textdecoder-nonascii.js        : duk.O2  2.97 duk.O2.master  3.15
test-textencoder-ascii.js           : duk.O2  4.63 duk.O2.master  4.64
test-textencoder-nonascii.js        : duk.O2 11.56 duk.O2.master 11.20
test-try-catch-nothrow.js           : duk.O2  2.72 duk.O2.master  2.74
test-try-catch-throw.js             : duk.O2 44.19 duk.O2.master 43.87
test-try-finally-nothrow.js         : duk.O2  3.29 duk.O2.master  3.40
test-try-finally-throw.js           : duk.O2 55.57 duk.O2.master 54.76
```

**Comment by svaarala** [comment]
Single linked list looks better overall:
- Single linking means string table removal needs to scan from the root so that the preceding string's `next` pointer can be updated. For a small load factor (<= 2.0 for example) this is a short scan on average. It's still variable as opposed to deterministic removal for double linking.
- The added cost of removal (on average a few pointer lookups) is offset by less pointer manipulation in inserts.

A few microbenchmarks:

```
test-string-array-concat.js         : duk.O2.oneway  6.21 duk.O2.twoway  6.25 duk.O2.200  6.38
test-string-arridx.js               : duk.O2.oneway  1.93 duk.O2.twoway  1.92 duk.O2.200  2.04
test-string-charlen-ascii.js        : duk.O2.oneway  1.15 duk.O2.twoway  1.23 duk.O2.200  1.19
test-string-charlen-nonascii.js     : duk.O2.oneway  2.88 duk.O2.twoway  2.83 duk.O2.200  2.85
test-string-compare.js              : duk.O2.oneway  2.43 duk.O2.twoway  2.28 duk.O2.200  2.40
test-string-decodeuri.js            : duk.O2.oneway  4.49 duk.O2.twoway  4.02 duk.O2.200  4.18
test-string-encodeuri.js            : duk.O2.oneway  4.79 duk.O2.twoway  4.73 duk.O2.200  4.83
test-string-garbage.js              : duk.O2.oneway  4.74 duk.O2.twoway  4.88 duk.O2.200  5.98
test-string-intern-grow-short.js    : duk.O2.oneway  4.62 duk.O2.twoway  4.84 duk.O2.200 13.64
test-string-intern-grow-short2.js   : duk.O2.oneway  4.79 duk.O2.twoway  4.60 duk.O2.200  5.59
test-string-intern-grow.js          : duk.O2.oneway  5.98 duk.O2.twoway  5.99 duk.O2.200 24.05
test-string-intern-grow2.js         : duk.O2.oneway  1.55 duk.O2.twoway  1.66 duk.O2.200  1.97
test-string-intern-match-short.js   : duk.O2.oneway  2.45 duk.O2.twoway  2.61 duk.O2.200  3.06
test-string-intern-match.js         : duk.O2.oneway  0.24 duk.O2.twoway  0.24 duk.O2.200  0.28
test-string-intern-miss-short.js    : duk.O2.oneway  2.99 duk.O2.twoway  3.06 duk.O2.200  3.99
test-string-intern-miss.js          : duk.O2.oneway  1.30 duk.O2.twoway  1.55 duk.O2.200  1.39
test-string-plain-concat.js         : duk.O2.oneway  0.99 duk.O2.twoway  1.00 duk.O2.200  1.00
test-string-uppercase.js            : duk.O2.oneway  2.78 duk.O2.twoway  2.81 duk.O2.200  3.81
```

Like always, these are not very accurate but the general trend seems to be that one-way linking is faster in practice.

**Comment by fatcerberus** [comment]
Hm, as an outsider looking in, it's hard for me to say based on those numbers alone.  The difference seems to be split roughly 50/50 and in any case, most of the numbers are very close (i.e. within 5%).  So I can't say I prefer either set of results over the other.  Half a dozen one or the other, as they say.

**Comment by svaarala** [comment]
The tests exercising the string table algorithms most are test-string-garbage.js and test-string-intern-*.js which are a mostly better (with one exception) using a single linked list. I'll rerun the performance tests with more runs before merging.

But as discussed earlier, changing any code anywhere affects code layout, which affects code caching, etc. This inaccuracy matters especially when measuring (1) the impact of small changes, and (2) for code that affects only a small portion of the runtime of any benchmark. That (2) is the case here: no test can really hit the string table hard without doing a lot of other stuff too, so the differences are hard to demonstrate. The differences may get lost in timing error (for which running the test more times helps) but also in systematic differences like code layout affecting performance (for which running the best more times *doesn't* help).

However, both the one- and two-way linked lists are clearly better than the algorithm in Duktape 2.0 (which dates back to Duktape 0.x). This is of course the most important decision in merging: each merge should ideally make master better.

In this kind of situations it's unfortunately partially up to measurement, and partially up to trying to reason what should work well.

**Comment by svaarala** [comment]
This is pretty much complete now. It's not a big deal with respect to performance because the string table only really affects tests with a lot of string churn. It does improve a few "corner case" tests though. The main benefits of this change is some footprint improvement (though there's some ROM string follow-up) and removal of the variant algorithms in favor of a single, more flexible one. I'll post a performance run result when it's complete and merge probably in a day or two.

**Comment by svaarala** [comment]
```
test-add-fastint.js                 : duk.O2  0.67 duk.O2.master  0.66
test-add-float.js                   : duk.O2  0.70 duk.O2.master  0.71
test-add-nan-fastint.js             : duk.O2  0.80 duk.O2.master  0.79
test-add-nan.js                     : duk.O2  0.69 duk.O2.master  0.68
test-arith-add.js                   : duk.O2  2.54 duk.O2.master  2.55
test-arith-div.js                   : duk.O2  7.28 duk.O2.master  7.27
test-arith-mod.js                   : duk.O2  6.64 duk.O2.master  6.72
test-arith-mul.js                   : duk.O2  3.93 duk.O2.master  3.92
test-arith-sub.js                   : duk.O2  2.78 duk.O2.master  2.79
test-array-append.js                : duk.O2  0.53 duk.O2.master  0.52
test-array-cons-list.js             : duk.O2  0.87 duk.O2.master  0.86
test-array-foreach.js               : duk.O2  2.70 duk.O2.master  2.62
test-array-literal.js               : duk.O2  1.64 duk.O2.master  1.59
test-array-pop.js                   : duk.O2  2.20 duk.O2.master  2.19
test-array-push.js                  : duk.O2  2.42 duk.O2.master  2.47
test-array-read-lenloop.js          : duk.O2  1.88 duk.O2.master  1.83
test-array-read.js                  : duk.O2  1.75 duk.O2.master  1.72
test-array-sort.js                  : duk.O2  3.39 duk.O2.master  3.42
test-array-write-length.js          : duk.O2  1.63 duk.O2.master  1.60
test-array-write.js                 : duk.O2  1.80 duk.O2.master  1.74
test-assign-add.js                  : duk.O2  3.71 duk.O2.master  3.71
test-assign-addto-nan.js            : duk.O2  1.32 duk.O2.master  1.31
test-assign-addto.js                : duk.O2  3.69 duk.O2.master  3.70
test-assign-boolean.js              : duk.O2  4.69 duk.O2.master  4.72
test-assign-const-int.js            : duk.O2  2.48 duk.O2.master  2.53
test-assign-const-int2.js           : duk.O2  5.85 duk.O2.master  5.86
test-assign-const.js                : duk.O2  4.01 duk.O2.master  4.04
test-assign-literal.js              : duk.O2  3.75 duk.O2.master  3.88
test-assign-proplhs-reg.js          : duk.O2  2.58 duk.O2.master  2.56
test-assign-proprhs.js              : duk.O2  2.83 duk.O2.master  2.67
test-assign-reg.js                  : duk.O2  2.86 duk.O2.master  2.78
test-base64-decode-whitespace.js    : duk.O2  1.85 duk.O2.master  1.91
test-base64-decode.js               : duk.O2  1.52 duk.O2.master  1.51
test-base64-encode.js               : duk.O2  1.71 duk.O2.master  1.71
test-bitwise-ops.js                 : duk.O2  1.83 duk.O2.master  1.83
test-break-fast.js                  : duk.O2  1.37 duk.O2.master  1.42
test-break-slow.js                  : duk.O2  7.35 duk.O2.master  7.40
test-buffer-nodejs-read.js          : duk.O2  2.27 duk.O2.master  2.26
test-buffer-nodejs-write.js         : duk.O2  2.94 duk.O2.master  2.90
test-buffer-object-read.js          : duk.O2  2.27 duk.O2.master  2.28
test-buffer-object-write.js         : duk.O2  2.92 duk.O2.master  2.91
test-buffer-plain-read.js           : duk.O2  1.84 duk.O2.master  1.83
test-buffer-plain-write.js          : duk.O2  1.76 duk.O2.master  1.79
test-call-basic-1.js                : duk.O2  7.69 duk.O2.master  7.66
test-call-basic-2.js                : duk.O2  7.64 duk.O2.master  7.66
test-call-basic-3.js                : duk.O2  9.58 duk.O2.master  9.49
test-call-basic-4.js                : duk.O2 17.67 duk.O2.master 17.27
test-call-native.js                 : duk.O2 13.74 duk.O2.master 13.34
test-call-prop.js                   : duk.O2  4.27 duk.O2.master  4.32
test-call-reg-new.js                : duk.O2  6.59 duk.O2.master  6.47
test-call-reg.js                    : duk.O2  3.07 duk.O2.master  3.03
test-call-var.js                    : duk.O2  7.87 duk.O2.master  7.83
test-compile-mandel-nofrac.js       : duk.O2 10.68 duk.O2.master 11.10
test-compile-mandel.js              : duk.O2 13.82 duk.O2.master 13.91
test-compile-short.js               : duk.O2  6.66 duk.O2.master  6.73
test-compile-string-ascii.js        : duk.O2  6.67 duk.O2.master  6.71
test-continue-fast.js               : duk.O2  1.77 duk.O2.master  1.82
test-continue-slow.js               : duk.O2  7.74 duk.O2.master  7.70
test-empty-loop-slowpath.js         : duk.O2  1.67 duk.O2.master  1.67
test-empty-loop.js                  : duk.O2  1.73 duk.O2.master  1.69
test-enum-basic.js                  : duk.O2  3.53 duk.O2.master  3.96
test-equals-fastint.js              : duk.O2  0.57 duk.O2.master  0.55
test-equals-nonfastint.js           : duk.O2  0.62 duk.O2.master  0.62
test-error-create.js                : duk.O2  2.13 duk.O2.master  2.19
test-fib.js                         : duk.O2  6.64 duk.O2.master  6.89
test-global-lookup.js               : duk.O2  8.00 duk.O2.master  7.83
test-hello-world.js                 : duk.O2  0.00 duk.O2.master  0.00
test-hex-decode.js                  : duk.O2  3.62 duk.O2.master  3.62
test-hex-encode.js                  : duk.O2  2.86 duk.O2.master  2.84
test-jc-serialize-indented.js       : duk.O2  3.36 duk.O2.master  3.33
test-jc-serialize.js                : duk.O2  2.29 duk.O2.master  2.17
test-json-parse-hex.js              : duk.O2  3.19 duk.O2.master  3.19
test-json-parse-integer.js          : duk.O2  2.82 duk.O2.master  3.78
test-json-parse-number.js           : duk.O2  5.05 duk.O2.master  5.17
test-json-parse-string.js           : duk.O2  4.67 duk.O2.master  5.73
test-json-serialize-fastpath-loop.js: duk.O2  3.50 duk.O2.master  3.58
test-json-serialize-forceslow.js    : duk.O2  9.16 duk.O2.master  9.22
test-json-serialize-hex.js          : duk.O2  1.47 duk.O2.master  1.47
test-json-serialize-indented-deep100.js: duk.O2  1.70 duk.O2.master  1.78
test-json-serialize-indented-deep25.js: duk.O2  3.17 duk.O2.master  3.15
test-json-serialize-indented-deep500.js: duk.O2  1.13 duk.O2.master  1.18
test-json-serialize-indented.js     : duk.O2  5.89 duk.O2.master  5.87
test-json-serialize-jsonrpc-message.js: duk.O2  1.98 duk.O2.master  1.99
test-json-serialize-nofrac.js       : duk.O2  0.61 duk.O2.master  0.61
test-json-serialize-plainbuf.js     : duk.O2  2.44 duk.O2.master  2.41
test-json-serialize-slowpath-loop.js: duk.O2  4.22 duk.O2.master  4.26
test-json-serialize.js              : duk.O2  6.08 duk.O2.master  5.86
test-json-string-bench.js           : duk.O2  3.45 duk.O2.master  3.46
test-json-string-stringify.js       : duk.O2  5.15 duk.O2.master  5.04
test-jx-serialize-bufobj-forceslow.js: duk.O2  4.32 duk.O2.master  4.81
test-jx-serialize-bufobj.js         : duk.O2  1.61 duk.O2.master  1.55
test-jx-serialize-indented.js       : duk.O2  3.34 duk.O2.master  3.34
test-jx-serialize.js                : duk.O2  2.20 duk.O2.master  2.21
test-mandel.js                      : duk.O2  2.96 duk.O2.master  3.01
test-object-garbage-2.js            : duk.O2  4.95 duk.O2.master  4.78
test-object-garbage.js              : duk.O2  4.62 duk.O2.master  4.52
test-object-literal.js              : duk.O2  2.86 duk.O2.master  2.75
test-prop-read-4.js                 : duk.O2  3.35 duk.O2.master  3.18
test-prop-read-8.js                 : duk.O2  3.62 duk.O2.master  3.42
test-prop-read.js                   : duk.O2  3.43 duk.O2.master  3.23
test-prop-write-1024.js             : duk.O2  3.25 duk.O2.master  3.85
test-prop-write-16.js               : duk.O2  3.66 duk.O2.master  3.58
test-prop-write-256.js              : duk.O2  3.90 duk.O2.master  3.30
test-prop-write-32.js               : duk.O2  3.27 duk.O2.master  3.33
test-prop-write-4.js                : duk.O2  2.92 duk.O2.master  2.88
test-prop-write-48.js               : duk.O2  3.26 duk.O2.master  3.30
test-prop-write-64.js               : duk.O2  3.44 duk.O2.master  3.35
test-prop-write-8.js                : duk.O2  3.18 duk.O2.master  3.12
test-prop-write.js                  : duk.O2  2.98 duk.O2.master  2.96
test-random.js                      : duk.O2  2.28 duk.O2.master  2.27
test-reg-readwrite-object.js        : duk.O2  3.12 duk.O2.master  3.04
test-reg-readwrite-plain.js         : duk.O2  2.02 duk.O2.master  2.01
test-regexp-case-insensitive.js     : duk.O2 25.78 duk.O2.master 24.87
test-regexp-compile.js              : duk.O2  2.11 duk.O2.master  2.19
test-regexp-execute.js              : duk.O2  1.46 duk.O2.master  1.50
test-regexp-string-parse.js         : duk.O2  5.89 duk.O2.master  6.16
test-strict-equals-fastint.js       : duk.O2  0.58 duk.O2.master  0.55
test-strict-equals-nonfastint.js    : duk.O2  0.61 duk.O2.master  0.61
test-string-array-concat.js         : duk.O2  5.51 duk.O2.master  5.51
test-string-arridx.js               : duk.O2  1.68 duk.O2.master  1.71
test-string-charlen-ascii.js        : duk.O2  1.07 duk.O2.master  1.08
test-string-charlen-nonascii.js     : duk.O2  2.64 duk.O2.master  2.63
test-string-compare.js              : duk.O2  2.09 duk.O2.master  2.08
test-string-decodeuri.js            : duk.O2  3.57 duk.O2.master  3.79
test-string-encodeuri.js            : duk.O2  4.00 duk.O2.master  4.03
test-string-garbage.js              : duk.O2  4.06 duk.O2.master  4.81
test-string-intern-grow-short.js    : duk.O2  3.96 duk.O2.master 11.61
test-string-intern-grow-short2.js   : duk.O2  3.89 duk.O2.master  4.50
test-string-intern-grow.js          : duk.O2  4.76 duk.O2.master 19.08
test-string-intern-grow2.js         : duk.O2  1.42 duk.O2.master  1.69
test-string-intern-match-short.js   : duk.O2  1.96 duk.O2.master  2.57
test-string-intern-match.js         : duk.O2  0.21 duk.O2.master  0.22
test-string-intern-miss-short.js    : duk.O2  2.24 duk.O2.master  3.08
test-string-intern-miss.js          : duk.O2  1.15 duk.O2.master  1.16
test-string-number-list.js          : duk.O2  0.78 duk.O2.master  1.13
test-string-plain-concat.js         : duk.O2  0.84 duk.O2.master  0.85
test-string-uppercase.js            : duk.O2  2.19 duk.O2.master  2.20
test-textdecoder-ascii.js           : duk.O2  2.83 duk.O2.master  2.52
test-textdecoder-nonascii.js        : duk.O2  2.79 duk.O2.master  2.96
test-textencoder-ascii.js           : duk.O2  3.99 duk.O2.master  4.26
test-textencoder-nonascii.js        : duk.O2 10.83 duk.O2.master 10.61
test-try-catch-nothrow.js           : duk.O2  2.54 duk.O2.master  2.58
test-try-catch-throw.js             : duk.O2 39.64 duk.O2.master 39.05
test-try-finally-nothrow.js         : duk.O2  3.28 duk.O2.master  3.28
test-try-finally-throw.js           : duk.O2 49.74 duk.O2.master 49.19
```

**Comment by fatcerberus** [comment]
Seeing how greatly most of the the string benchmarks benefit from this change, I wonder now how this will affect TypeScript/Babel transpilation performance.  If I remember from my profiling results, string manipulation was one of the biggest time sinks.

**Comment by svaarala** [comment]
The crucial thing is how many strings are created on-the-fly -- those involve string hashing, and a string table lookup to see if they're already interned. Most practical code will create surprisingly few strings on the fly; strings tend to be constants and such. But transpilation might indeed be one of those cases so it'd be interesting if this has a measurable effect (my guess would be, unfortunately, no).

Another possible bottleneck is the string accumulation using:

```js
var res = ''
for (;;) {
    // ...
    res += something;
}
```

This performs well on some engines, but Duktape doesn't support "ropes" or other string structures which would make that efficient. Instead, every copy gets interned.

Even a single loop like this can be a major bottleneck, if the loop is used to create e.g. 10 kB result string.

**Comment by svaarala** [comment]
The concatenation idiom is common enough so that it may be useful to support it somehow. Not sure yet how easy that would be compared to the benefits.

The main approaches are:

- Reworking the string data structure somehow (example below).
- Making the compiler recognize the idiom and do something more sensible. The compiler change is rather difficult because one would need to analyze loops, potential indirect accesses to the accumulation variable, etc, so this would only really be possible after a compiler rework. And even then it's relatively complicated analysis for a low memory target.

One example of a string data structure change:
- Make the `duk_hstring` always use an explicit data pointer for the actual string data. Currently `duk_hstring` header is followed by the data directly.
- Make the string structure lazy: string is either (1) finalized, or (2) pending. In the pending state the string could contain a snippet, and a prefix/suffix pointer. For example, "foo" + "bar" would create a duk_hstring whose initial part was "foo" and the suffix was (another duk_hstring) "bar".
- When strings are concatenated, the operation can be lazy. Each concatenation step creates a new `duk_hstring` with e.g. a single character and a prefix pointer.
- When a string is read, the internals would either (a) flatten the string at that point to its final form, or (b) all string handling sites would support "ropes" (less likely to be viable).
- Byte and character length can be computed upfront (for concatenation that's pretty cheap, assuming valid UTF-8 strings).
- String hash, "arridx flag", and actual string data would need to be lazily computed. Lazy string hash would be a string table issue, so maybe it would need to be computed during concatenation - which means string hash would ideally be defined so that it could be computed incrementally during concatenation (not trivial, and might make the hash worse).
- Strings might be flattened even during concatenation using some heuristic, or e.g. random selection based on the string hash. This would ensure that the ropes would be periodically straightened out and the number of individual heap allocated `duk_hstring` instances would be kept in check even during the accumulation phase.

This is obviously not efficient compared to actually accumulating a string efficiently like C code would do. But compared to current behavior this is much faster; the current behavior will process O(n^2) bytes for memory copying, string hashing, character length computation, etc. Using lazy strings as above would be closer to O(n) (at least in practice), provided that character length and string hash could be either delayed too (and avoided for intermediate results) or computed incrementally.

**Comment by fatcerberus** [comment]
One of the tradeoffs (I think) is equality comparison (`==` and `===`), which right now, because of eager interning, can be done with a simple pointer comparison.  With a change like the above, equality would either need an intern check or a character-by-character comparison.

**Comment by svaarala** [comment]
Yeah :( The ropes could resolve to the same strings, and because the `duk_hstring` itself couldn't be merged with an existing string, multiple `duk_hstrings` could end up having the same data -- or at least pointing to the same data area which would then need some form of reference counting to be managed correctly.

There may still be some way around content comparison though. For example, the finalized data areas could have a unique number (running number) assigned by interning. String comparison would finalize the strings involved which would flatten the data and check if an existing finalized data area exists for that result. The string comparison could then compare those running numbers.

But it's definitely an added complication and breaks the "each string has at most one duk_hstring representing it" situation.

**Comment by svaarala** [comment]
Maybe one approach would be to add a separate internal type for a "string temporary". It would test true for "is string" but when you wanted to access the string data (either `const char *` or `duk_hstring *`) it would be converted in place to an actual `duk_hstring` and be interned in that step. This would keep the current `duk_hstring` uniqueness guarantees at the cost of an additional internal type to deal with. It would also be natural for string temporaries to have no fields like blen, clen, arridx, or strhash - they would be computed in the duk_hstring conversion, and only for a result value that actually gets coerced into a duk_hstring.

If the type was (internally) tagged, it wouldn't have a major impact on existing string paths because it would just be another entry in the switch-case jump table at relatively little cost.

But I'm sure there are some nitty gritty details to deal with here :-)

**Comment by fatcerberus** [comment]
So basically it would work something like a "string builder" in other frameworks, but managed internally and not observable to outside code?  That's an interesting idea.

**Comment by svaarala** [comment]
> So basically it would work something like a "string builder" in other frameworks, but managed internally and not observable to outside code?

That's one way to put it, and maybe a more useful way in practice too. Thinking along those lines:

```js
// Original
res += something;

// Internal (very conceptually :-)
res_stringBuilder = new StringBuilder(res_stringBuilder).append(something);
```

If there's a guarantee that there are no other references to the stringbuilder (which should be possible from refcount, and is quite often the case in accumulation):

```js
// Internal, when refcount = 1
res_stringBuilder.append(something);
```

A refcount check would work correctly in the sense that if the loop just appended stuff to the stringbuilder, it wouldn't get copied. Being able to do the accumulation in place would allow an efficient concatenation algorithm without creating a lot "rope" temporaries.

The downside is that in a non-refcount build the refcount peeking isn't available. It would still be possible to implement the stringbuilder efficiently, e.g. by allowing it to work *only* in a register-allocated variable and not allowing the variable to be copied without flattening to an actual string. This way there would always be just one reference which would get flattened on a copy or when accessed as an actual string.

Lots of options ultimately :-)

**Pull request merged**
