### PR TITLE
Avoid variables named "index" which may cause -Wshadow warnings

### PR DESCRIPTION
**Pull request by svaarala**
- [x] Rename `index` -> `idx` in sources
- [x] Rename in website and API documentation
- [x] Code issues note
- [x] Regression testing; could codepolicycheck detect a blacklist of bad names?
- [x] Releases entry

### CODE REVIEW

**Comment by svaarala** [comment]
There are no issues on my local build or the testrunner runs (which run on some Ubuntu variant), but there are a lot of warnings in the Travis environment.

**Comment by svaarala** [comment]
Ok, the build warnings seem to be fixed, though I get this weird empty error in Travis output:

```
duk_api_time.c: In function ‘duk_time_to_components’:

linenoise/linenoise.c: In function ‘linenoiseNoTTY’:
linenoise/linenoise.c:1015:13: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
linenoise/linenoise.c:1022:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
```

The linenoise warnings are expected but the duk_api_time.c seems like broken compiler output (I've seen similar issues with GCC warnings sometimes, and it's difficult to figure out why).

I'll see if I can add some check to codepolicycheck to catch this (it's pretty easy to imagine using a variable named "index" at some point in the future after all... :). Let's hope no platform defines, say, `i`.

**Comment by fatcerberus** [comment]
> Let's hope no platform defines, say, i

Hehe.  But I thought the `index` being shadowed was in Duktape (not platform) code anyway?

**Comment by svaarala** [comment]
No, Duktape just uses an argument/variable named `index` which shadows a function `index()` defined in strings.h.

**Comment by svaarala** [comment]
Related: http://stackoverflow.com/questions/22028651/how-to-suppress-shadow-index-warning.

**Comment by fatcerberus** [comment]
Ah.  That's pretty annoying then.

**Comment by svaarala** [comment]
One platform I worked on a few years ago defined constants like `C1`, `X4`, etc in platform headers. This caused a lot of conflicts with e.g. MD5 implementations. C is not without its problems :)

**Comment by fatcerberus** [comment]
Hm, so it's apparently related to older GCC versions because it was fixed in GCC 4.8.

**Comment by svaarala** [comment]
Yeah, it's version specific quite clearly (I'm guessing this shadowing issue would turn up pretty often). But it'd no big deal avoiding "index" as a variable/argument name. I'll just have to figure out how to detect it for commit tests so I won't break it again at some later time :)

**Comment by svaarala** [comment]
It seems codepolicycheck identifier pattern is good enough, so just blacklisting "index" works:

    vim +331   src/duk_api_public.h.in : invalid identifier 'index' (perhaps plain)  - DUK_EXTERNAL_DECL duk_idx_t duk_normalize_index(duk_context *ctx, duk_idx_t index);

**Comment by svaarala** [comment]
Ok, now I got the time related shadow warning without it getting garbled:

```
duk_api_time.c:11:73: warning: declaration of ‘time’ shadows a global declaration [-Wshadow]
```

Fixed that too.

**Pull request merged**
