### PR TITLE
Base integration of duktape with the Fuzzilli Javascript engine fuzzer

### PR DESCRIPTION
**Pull request by WilliamParks**
This covers basic integration with Fuzzilli. It can be used with my branch of Fuzzilli [here](https://github.com/WilliamParks/fuzzilli-1/tree/duktape_integration), with run commands listed in examples/fuzzilli/README.rst in this PR

Still a little ways out from being fully integrated, as optimizations of the fuzz target are needed, tracked in #2319

### CODE REVIEW

**Comment by svaarala** [comment]
Thanks, I'll look this over tonight. One question at the outset:

Are the changes required to duk_cmdline.c large enough to warrant a separate duk_fuzzilli.c file? If the changes needed can be managed with some `#ifdef`s then it'd be great to avoid duplicating much of the code. (I'll check the concrete diff tonight when I get a chance.)

**Comment by WilliamParks** [comment]
> Are the changes required to duk_cmdline.c large enough to warrant a separate duk_fuzzilli.c file? If the changes needed can be managed with some #ifdefs then it'd be great to avoid duplicating much of the code. (I'll check the concrete diff tonight when I get a chance.)

As of right now, most likely not. However, I'm planning on doing an iteration of over duk_fuzzilli to remove all the unnecessary options for it/checks/etc on startup. One of the performance limitations right now is that the timeout for duktape is > 2x what it is for other engines, which I believe is due to the startup costs.

If that's wrong or I can't get a meaningful speedup, I can move it back into duk_cmdline.c

**Comment by svaarala** [comment]
> One of the performance limitations right now is that the timeout for duktape is > 2x what it is for other engines, which I believe is due to the startup costs.

That's surprising considering that e.g. Node.js startup is way higher than for Duktape (for understandable reasons):
```
$ time ./duk /tmp/hello.js 
hello world!

real	0m0.002s
user	0m0.000s
sys	0m0.002s

$ time nodejs /tmp/hello.js 
hello world!

real	0m0.041s
user	0m0.039s
sys	0m0.000s
```

Could the same running process be reused for multiple tests?

**Comment by WilliamParks** [comment]
> Could the same running process be reused for multiple tests?

Currently, Fuzzilli runs 100x unique input programs in one process, and resets the engine state between each one!

I looked at how Fuzzilli calculates its recommended timeouts, and ran some tests. It runs a loop 1000 times that makes an object and calls a function that does property look ups. Their builder for that is [here](https://github.com/googleprojectzero/fuzzilli/blob/master/Sources/Fuzzilli/Fuzzer.swift#L313)

Setting the loop to run just once results in similar times for duktape and V8, which disproves my theory. It makes sense given that V8 and Duktape are built for different use cases.

Fuzzilli recommended timeout for 1000x executions of the loop
V8: 100ms 
Duktape:  790ms

Fuzzilli recommended timeout for 1x execution of the loop
V8: 70ms
Duktape: 100ms

That leaves the following TBD:
- Deciding if it's worth the time to reduce the unused code compiled into duk-fuzzilli, in order to get more meaningful coverage numbers
- Deciding whether duk-fuzzilli should be it's own folder in /examples, or based on defines in duk_cmdline

**Comment by svaarala** [comment]
Since Duktape is a plain bytecode interpreter (no JIT), it is typically 10-100x slower than a JIT engine. This will probably be an important factor to consider w.r.t. timeouts.

**Comment by svaarala** [comment]
Would you like this to be merged, with follow-ups for cleanups? If so, could you please rebase into a single commit (or a few topic commits)?

**Comment by WilliamParks** [comment]
> Would you like this to be merged, with follow-ups for cleanups? If so, could you please rebase into a single commit (or a few topic commits)?

I'd like to wait until we've figured out the coverage issue, and whether or not it should be it's own folder vs defines in duk_cmdline, if that's alright with you. Once I get your thoughts on those two issues, I'll implement them and clean up the commit history.

**Comment by svaarala** [comment]
Sure, no hurry to merge :)

**Comment by WilliamParks** [comment]
I moved things back to duk_cmdline, and squashed the commits. Should be good to merge!

Running the fuzzer can be done with `swift run -c release FuzzilliCli --profile=duktape --storagePath=./output --timeout=1000 ./duk-fuzzilli`, from my branch of fuzzilli [here](https://github.com/WilliamParks/fuzzilli-1/tree/duktape_integration)

Running in a docker container from the main fuzzilli repo will be a straightforward addition once I have a permanent place to point the docker build script at.

Also, @svaarala what's the best place to put a short piece of documentation (mainly the above) in duktape on how to run fuzzilli?

**Comment by svaarala** [comment]
Thanks, I'll check the diff out by tomorrow.

Re: dockerization, Docker usage in this repo is a work in progress:
- docker/ contains various Docker images, most sharing a (large) base image such as docker/duktape-base-ubuntu-18.04-x64.
- Images are not (yet) published, but one builds them locally using e.g. `make docker-images`.
- Docker images are not yet used for anything critical in the repo, but my intent is to rework most targets to rely on Docker to reduce the developer hassle with host differences. If one doesn't want to use Docker, the Dockerfiles are still useful as they basically document the required packages.
- Docker images by convention pass input and output files as ZIP files via stdin/stdout. This may seem odd, but it avoids file owner and permission issues.

So for now, it'd be fine to just add a new directory to docker/. If it's possible, it would be nice to reuse a base image like docker/duktape-base-ubuntu-18.04-x64 because it reduces the disk requirements. But it'd be also fine to download a prebuilt image (or a Dockerfile) from somewhere as long as that image is available indefinitely.

Re: documentation, one easy approach is to add a fuzz target to the Makefile and just refer to it from the README ("Run `make xxx` for Fuzzilli-based automatic fuzzing tests, see the Makefile target for details."). If you want to document the setup more, `doc/fuzzilli.rst` would be a good place.

**Comment by svaarala** [comment]
I'll merge this as is, and clean up some trivia in a follow-up. We can then look at next steps. Thanks! :+1:

**Comment by svaarala** [comment]
@WilliamParks Here's the follow-up: https://github.com/svaarala/duktape/pull/2329. Most of it is indentation and style trivia - you may want to read with `git diff -w` to avoid the whitespace diff (hard tabs should be used throughout).

Could you check that fuzzing still works i.e. I didn't break anything before I merge? :)

Substance changes:
- Simplify fuzzilli() binding by using nargs=2 when registering the function, and using duk_require_string() instead of checking for types.
- Declare duk_assert_wrapper() in duktape public header when DUK_USE_FUZZILLI is enabled, as it is in effect part of the API in this case. (Maybe duk_assert() could be exposed just generally.)
- Hoist declarations of variables to beginning of block (Duktape code base is C89 compatible generally, although it doesn't matter here).

When the REPRL loop is running, should there be a clean exit path, or does the loop (if it starts) always terminate via an error?

**Comment by WilliamParks** [comment]
> Could you check that fuzzing still works i.e. I didn't break anything before I merge? :)

I'm going to run it for a couple hours as a sanity check (looks good right now), and look through your changes in the mean time. 

> So for now, it'd be fine to just add a new directory to docker/. If it's possible, it would be nice to reuse a base image like docker/duktape-base-ubuntu-18.04-x64 because it reduces the disk requirements. But it'd be also fine to download a prebuilt image (or a Dockerfile) from somewhere as long as that image is available indefinitely.

There currently aren't any Fuzzilli images that get pushed out. That repo has build scripts to easily package everything, however [link](https://github.com/googleprojectzero/fuzzilli/tree/master/Cloud/Docker). I've got a version of that for duktape implemented locally. What'd be the best way of integration? A script to pull down the fuzzilli repo and run it's build script would be straightforward, if a bit convoluted.

**Comment by svaarala** [comment]
Sounds like adding two targets to the Makefile might be the easiest first step, something like this:
- `make docker-image-fuzzilli`: clone the fuzzilli repo, build the Docker image locally, tag it as `duktape-fuzzilli` or similar. Include the duktape-fuzzilli docker image in the `docker-clean` target.
- `make fuzztest`: run fuzzilli testing, expecting the tagged Docker image to exist locally.

I don't think it needs to be cleaner than this at present.

**Comment by WilliamParks** [comment]
> When the REPRL loop is running, should there be a clean exit path, or does the loop (if it starts) always terminate via an error?

The fuzzer itself sends sigkill to the child to end the loop. Implemented [here](https://github.com/googleprojectzero/fuzzilli/blob/2e7c967d171a5059aff6f9ab8df6be0e36216018/Sources/Fuzzilli/Execution/REPRL.swift#L121)

> Sounds like adding two targets to the Makefile might be the easiest first step, something like this:

Makes sense. After the cleanup merge is complete, I'll push the docker implementation on the fuzzilli side, and finish things up with the make target here.

**Pull request merged**
