### PR TITLE
Minor cleanups to Math.cbrt() etc

### PR DESCRIPTION
**Pull request by svaarala**
- [x] Make function pointers in math table conditional to `DUK_USE_ES6` or replace them with `duk__math_nop()` when ES6 not enabled (footprint)
- [x] Extend Math.log2() 2^N testcase for all IEEE double exponents (separate testcase)
- [x] Precomputation for `/ DUK_LOG(2)` and `/ DUK_LOG(10)` in fallback path

### CODE REVIEW

**Comment by svaarala** [comment]
```
> expect = 0; x = 1; while (x !== 1/0) { if (Math.log2(x) != expect) { console.log(x, Math.log2(x)); } x *= 2; expect++; }
1023
> expect = 0; x = 1; while (x !== 0) { if (Math.log2(x) != expect) { console.log(x, Math.log2(x)); } x /= 2; expect--; }
-1074
```

**Comment by fatcerberus** [comment]
Don't forget to make `Math.hypot()` conditional too.

**Comment by fatcerberus** [comment]
Regarding that test above, why do positive exponents only go up 1023 but negative exponents go to -1074?  Based on my (somewhat limited) knowledge of IEEE floating point representation I'd have thought it would be symmetric in both directions.

**Comment by svaarala** [comment]
The exponent range doesn't but in the negative direction there are denormals which make up the difference.

**Comment by svaarala** [comment]
Math.hypot() is already conditional and it's not part of the function pointer tables so it should already be OK.

**Comment by fatcerberus** [comment]
Ah, that's right, I forgot it has its own function because it's vararg.

**Pull request merged**
