### PR TITLE
Replace gcc by $(CC) in Makefile.sharedlibrary and other dist Makefiles

### PR DESCRIPTION
**Pull request by ffontaine**
This patch will allow cross-compilation

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by svaarala** [comment]
Please add yourself to AUTHORS (first list, not second), see CONTRIBUTING.

Re: the change itself, I can merge it to master but the Makefiles in the distributable are examples only. They're not maintained for a set of actual targets because there are quite many of them and a variety of different build systems are used.

**Comment by svaarala** [comment]
If this is merged to master I think the equivalent change should be made to all the dist (and extras) Makefiles that go into the final distributable. I can do that as a separate pull.

**Comment by ffontaine** [comment]
Thanks for your review, I updated my PR with AUTHORS as well as updates to other Makefiles in dist but I forgot the Makefile in the extra folder. If you want, I can update my PR again or I can create a new one for this folder.

**Comment by svaarala** [comment]
Thanks! If you have time a separate pull for the extras folder would be nice for consistency (I can do that also if necessary).

Re: the updated diff, should `CC = gcc` be `CC ?= gcc` throughout so that CC can be passed in from outside? There seem to be various conventions so I'm not sure what's the most common one.

**Comment by fatcerberus** [comment]
It's been my experience that `CC=gcc` still allows you to override it, at least under Linux.

**Comment by svaarala** [comment]
With CC=gcc you can override it as:
```
$ make test CC=foo
```

but not as:
```
$ CC=foo make test
```

The `CC ?= gcc` form works in both cases. Not sure which is the better practice though.

**Comment by svaarala** [comment]
@ffontaine I'm OK with `CC = gcc` if the behavior is as intended - let me know if I should merge this as is.

**Comment by svaarala** [comment]
As a sidenote, while it's not a problem here, overriding just CC is in general not enough because also the compiler options may need some overriding, and things get really messy when compiler or even compiler version specific options are used in complex ways (say PGO and two-pass compilation). Consequently, making really portable Makefiles involves a lot of trivia.

While that's an interesting challenge, I'm not personally very interested that, and explains why I've tried to keep the Makefiles merely as examples rather than being actually maintained portable Makefiles working on a wide variety of targets. There are simply more interesting things to spend time on, especially considering many users don't like Makefiles and prefer SCons, various IDEs, etc :)

**Comment by ffontaine** [comment]
`CC = gcc` is the intended use, I changed this to keep some consistency with the Makefiles that were already defining CC such as Makefile.cmdline or Makefile.dukdebug. I will send you a new PR for the extra folder ASAP.

**Pull request merged**
