### PR TITLE
Fix some clang -Wshorten-64-to-32 warnings

### PR DESCRIPTION
**Pull request by svaarala**
See #1560.

### CODE REVIEW

**Comment by svaarala** [comment]
@mike-lischke It'd be good if you could verify that you no longer get warnings from this branch. I tried to reproduce the warnings by adding -Wshorten-64-to-32 but quite likely my warning option set (and clang version) is still different.

**Comment by mike-lischke** [comment]
Ah good. Will test it in the coming week, thanks. Btw. why don't enable -Wall instead of specific warnings?

**Comment by svaarala** [comment]
I do enable -Wall and even -Wextra, but despite the name they don't enable all warning options.

**Comment by svaarala** [comment]
For example, my Clang supports -Wshorten-64-to-32 but it's not enabled by default, with -Wall, or even with -Wextra. This makes it difficult to achieve warning free compilation because the warning set depends on the compiler, and some of the opt-in warnings are quite limiting (for example, there's a warning for potentially truncating a snprintf(), which is sometimes quite intentional).

**Comment by mike-lischke** [comment]
I can confirm these warnings are gone. However, new warnings just came up with XCode 9:

```
duktape.c:13668:83: warning: possible misuse of comma operator here [-Wcomma]
                        p = DUK_BW_ENSURE_RAW(thr, bw_ctx, 1U + 4U + DUK_HSTRING_GET_BYTELEN(h_str), p),
                                                                                                       ^
duktape.c:13668:4: note: cast expression to void to silence warning
                        p = DUK_BW_ENSURE_RAW(thr, bw_ctx, 1U + 4U + DUK_HSTRING_GET_BYTELEN(h_str), p),
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                        static_cast<void>(                                                             )
duktape.c:16073:70: warning: possible misuse of comma operator here [-Wcomma]
                vals[DUK__IDX_PBYTES] = (duk_int_t) DUK_HOBJECT_P_ALLOC_SIZE(h_obj),
                                                                                   ^
duktape.c:16073:3: note: cast expression to void to silence warning
                vals[DUK__IDX_PBYTES] = (duk_int_t) DUK_HOBJECT_P_ALLOC_SIZE(h_obj),
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                static_cast<void>(                                                 )
duktape.c:63122:33: warning: variable 'act' may be uninitialized when used here [-Wconditional-uninitialized]
        duk__call_env_setup(thr, func, act, idx_args);
                                       ^~~
duktape.c:62947:21: note: initialize the variable 'act' to silence this warning
        duk_activation *act;
                           ^
                            = nullptr
duktape.c:63140:29: warning: variable 'nregs' may be uninitialized when used here [-Wconditional-uninitialized]
                duk_set_top_and_wipe(thr, nregs, nargs);
                                          ^~~~~
duktape.c:62944:17: note: initialize the variable 'nregs' to silence this warning
        duk_idx_t nregs;            /* # total registers target function wants on entry (< 0 => "as is") */
                       ^
                        = 0
duktape.c:63140:36: warning: variable 'nargs' may be uninitialized when used here [-Wconditional-uninitialized]
                duk_set_top_and_wipe(thr, nregs, nargs);
                                                 ^~~~~
duktape.c:62943:17: note: initialize the variable 'nargs' to silence this warning
        duk_idx_t nargs;            /* # argument registers target function wants (< 0 => "as is") */
                       ^
                        = 0
duktape.c:63134:37: warning: variable 'vs_min_bytes' may be uninitialized when used here [-Wconditional-uninitialized]
        duk_valstack_grow_check_throw(thr, vs_min_bytes);
                                           ^~~~~~~~~~~~
duktape.c:62945:25: note: initialize the variable 'vs_min_bytes' to silence this warning
        duk_size_t vs_min_bytes;    /* minimum value stack size (bytes) for handling call */
                               ^
                                = 0
6 warnings generated.
```

Can you pls fix them too :-)?

**Comment by svaarala** [comment]
Sure :)

**Comment by fatcerberus** [comment]
I love how it’s suggesting to add `static_cast<void>(...)` to a C file -_-

**Comment by svaarala** [comment]
In many cases the compiler is complaining about something being potentially unused simply because it doesn't always understand that an internal guarantee or an error check (causing a longjmp) guards against the situation. It's kind of frustrating to add code to explicitly initialize stuff for these cases because it never gets executed and typically does increase footprint. But... I'll do it, grudgingly ;) (And this isn't the case for all the warnings by a long shot, just a sidenote.)

**Comment by svaarala** [comment]
Those -Wcomma warnings are real, the rest are use_tailcall related warnings where the compiler doesn't seem to fully analyze that e.g. nregs is set either via tailcall or non-tailcall setup (mediated by use_tailcall which probably confuses the compiler). I'll see if I can restructure that code. Initializing e.g. act to NULL would silence to warning but would be pretty pointless because if it ever mattered, it would cause a segfault anyway (and if the warning was in fact accurate this would then make the bad behavior silent).

**Comment by mike-lischke** [comment]
@fatcerberus I compile duktape.c as C++ code, since I use C++ exceptions.

**Pull request merged**
