### PR TITLE
Use a more sparse string hash

### PR DESCRIPTION
**Pull request by svaarala**
Use a more sparse string hash. Current draft adapted from Lua 5.1.5 with some modifications. Bernstein's hash seems a slightly better candidate.

A more sparsely sampled string hash improves string handling performance but makes the string hash a little bit lower quality. Because string hashes are really only used for (1) quick rejects during hash comparisons, (2) for maintaining the string table hash structure, and (3) for maintaining object property table hash structure, they don't really require a high quality string hash. On the other hand, in some environments it might be more important to minimize the chance of similar strings getting the same hash than optimizing performance.

Not sure whether to merge this as is, or if to provide the old and new hashes behind an option. For environments where string hash collisions matter more (perhaps some sandboxing situations where code is potentially malicious) it might be nicer to use a more dense hash, perhaps even hashing the entire string instead of skipping parts (as was done in the old algorithm).

Tasks:

- [x] Performance measure the algorithm alternatives, inspecting x64, x86, and x32 code
- [x] Decide if string hash variants are needed
- [x] Go through alternatives in http://eternallyconfuzzled.com/tuts/algorithms/jsw_tut_hashing.aspx, e.g.: Bernstein, FNV, One-at-a-Time
- [x] Deprecate DUK_USE_HASHBYTES_UNALIGNED_U32_ACCESS
- [x] Make hash density (shift) a config option, so that if density is an issue it can be tuned easily, DUK_USE_STRHASH_SKIP_SHIFT
- [x] Bernstein hash init value 5381 vs. hash seed
- [x] Make original Murmurhash2 algorithm skip handling shift based => future work note
- [x] Releases entry

Some links:

- http://eternallyconfuzzled.com/tuts/algorithms/jsw_tut_hashing.aspx
- http://isthe.com/chongo/tech/comp/fnv/
- http://stackoverflow.com/questions/114085/fast-string-hashing-algorithm-with-low-collision-rates-with-32-bit-integer
- https://en.wikipedia.org/wiki/List_of_hash_functions#Non-cryptographic_hash_functions
- http://www.cse.yorku.ca/~oz/hash.html

### CODE REVIEW

**Comment by svaarala** [comment]
```
test-add-fastint.js             : duk.O2.strhash  0.08 duk.O2.master  0.09 duk.O2.130  0.13
test-add-float.js               : duk.O2.strhash  0.10 duk.O2.master  0.09 duk.O2.130  0.13
test-add-nan-fastint.js         : duk.O2.strhash  0.10 duk.O2.master  0.11 duk.O2.130  0.13
test-add-nan.js                 : duk.O2.strhash  0.10 duk.O2.master  0.09 duk.O2.130  0.13
test-array-read.js              : duk.O2.strhash  1.99 duk.O2.master  2.02 duk.O2.130  2.32
test-array-write.js             : duk.O2.strhash  3.01 duk.O2.master  2.97 duk.O2.130  2.90
test-assign-add.js              : duk.O2.strhash  5.77 duk.O2.master  5.90 duk.O2.130  9.95
test-assign-addto-nan.js        : duk.O2.strhash  1.63 duk.O2.master  1.65 duk.O2.130  2.42
test-assign-addto.js            : duk.O2.strhash  5.95 duk.O2.master  5.78 duk.O2.130 10.10
test-assign-const-int.js        : duk.O2.strhash  2.88 duk.O2.master  2.51 duk.O2.130  7.37
test-assign-const.js            : duk.O2.strhash  3.85 duk.O2.master  3.84 duk.O2.130  6.23
test-assign-literal.js          : duk.O2.strhash  4.45 duk.O2.master  4.46 duk.O2.130  7.27
test-assign-reg.js              : duk.O2.strhash  3.06 duk.O2.master  3.07 duk.O2.130  2.86
test-bitwise-ops.js             : duk.O2.strhash  0.75 duk.O2.master  0.73 duk.O2.130  0.89
test-break-fast.js              : duk.O2.strhash  1.70 duk.O2.master  1.65 duk.O2.130  1.51
test-break-slow.js              : duk.O2.strhash  7.96 duk.O2.master  8.12 duk.O2.130 11.70
test-buffer-nodejs-read.js      : duk.O2.strhash  2.48 duk.O2.master  2.50 duk.O2.130  2.50
test-buffer-nodejs-write.js     : duk.O2.strhash  3.29 duk.O2.master  3.31 duk.O2.130  3.42
test-buffer-object-read.js      : duk.O2.strhash  2.48 duk.O2.master  2.50 duk.O2.130  2.51
test-buffer-object-write.js     : duk.O2.strhash  3.31 duk.O2.master  3.29 duk.O2.130  3.41
test-buffer-plain-read.js       : duk.O2.strhash  2.02 duk.O2.master  2.05 duk.O2.130  2.06
test-buffer-plain-write.js      : duk.O2.strhash  1.93 duk.O2.master  1.95 duk.O2.130  1.80
test-call-basic-1.js            : duk.O2.strhash  9.31 duk.O2.master  9.43 duk.O2.130 12.59
test-call-basic-2.js            : duk.O2.strhash  9.31 duk.O2.master  9.26 duk.O2.130 12.44
test-call-basic-3.js            : duk.O2.strhash 14.90 duk.O2.master 14.97 duk.O2.130 20.01
test-call-basic-4.js            : duk.O2.strhash 37.24 duk.O2.master 36.56 duk.O2.130 46.56
test-call-native.js             : duk.O2.strhash 14.70 duk.O2.master 15.13 duk.O2.130 19.34
test-compile-mandel-nofrac.js   : duk.O2.strhash 13.47 duk.O2.master 13.44 duk.O2.130 13.58
test-compile-mandel.js          : duk.O2.strhash 16.75 duk.O2.master 16.65 duk.O2.130 16.81
test-compile-short.js           : duk.O2.strhash 10.32 duk.O2.master 10.12 duk.O2.130 10.39
test-continue-fast.js           : duk.O2.strhash  2.24 duk.O2.master  2.19 duk.O2.130  1.96
test-continue-slow.js           : duk.O2.strhash  8.34 duk.O2.master  8.51 duk.O2.130 12.11
test-empty-loop.js              : duk.O2.strhash  2.52 duk.O2.master  2.48 duk.O2.130  2.39
test-fib.js                     : duk.O2.strhash  8.03 duk.O2.master  7.86 duk.O2.130  9.85
test-global-lookup.js           : duk.O2.strhash 10.49 duk.O2.master 11.59 duk.O2.130 10.29
test-hello-world.js             : duk.O2.strhash  0.00 duk.O2.master  0.00 duk.O2.130  0.00
test-hex-decode.js              : duk.O2.strhash  5.45 duk.O2.master  5.47 duk.O2.130  5.46
test-hex-encode.js              : duk.O2.strhash 15.25 duk.O2.master 15.23 duk.O2.130 27.30
test-json-integer-parse.js      : duk.O2.strhash  0.42 duk.O2.master  0.42 duk.O2.130  0.43
test-json-number-parse.js       : duk.O2.strhash  5.36 duk.O2.master  5.29 duk.O2.130  5.23
test-json-serialize.js          : duk.O2.strhash  1.55 duk.O2.master  1.54 duk.O2.130  1.62
test-json-string-bench.js       : duk.O2.strhash  5.45 duk.O2.master  5.47 duk.O2.130  5.60
test-json-string-parse.js       : duk.O2.strhash  0.56 duk.O2.master  0.59 duk.O2.130  0.59
test-json-string-stringify.js   : duk.O2.strhash  1.04 duk.O2.master  1.06 duk.O2.130  1.33
test-mandel.js                  : duk.O2.strhash  4.66 duk.O2.master  4.68 duk.O2.130  4.82
test-prop-read.js               : duk.O2.strhash  4.86 duk.O2.master  5.01 duk.O2.130  5.37
test-prop-write.js              : duk.O2.strhash  4.52 duk.O2.master  4.46 duk.O2.130  4.56
test-reg-readwrite-object.js    : duk.O2.strhash  3.24 duk.O2.master  3.26 duk.O2.130  3.87
test-reg-readwrite-plain.js     : duk.O2.strhash  2.18 duk.O2.master  2.16 duk.O2.130  2.56
test-regexp-string-parse.js     : duk.O2.strhash 10.50 duk.O2.master 10.59 duk.O2.130 10.80
test-string-array-concat.js     : duk.O2.strhash  6.55 duk.O2.master  6.46 duk.O2.130  6.59
test-string-charlen-ascii.js    : duk.O2.strhash  1.38 duk.O2.master  1.62 duk.O2.130  5.41
test-string-charlen-nonascii.js : duk.O2.strhash  2.87 duk.O2.master  3.09 duk.O2.130  4.00
test-string-compare.js          : duk.O2.strhash  3.89 duk.O2.master  3.88 duk.O2.130  3.86
test-string-decodeuri.js        : duk.O2.strhash  3.65 duk.O2.master  3.66 duk.O2.130  3.67
test-string-encodeuri.js        : duk.O2.strhash  4.10 duk.O2.master  4.17 duk.O2.130  4.45
test-string-intern-match.js     : duk.O2.strhash  0.40 duk.O2.master  0.99 duk.O2.130  0.99
test-string-intern-miss.js      : duk.O2.strhash  1.37 duk.O2.master  2.04 duk.O2.130  2.58
test-string-plain-concat.js     : duk.O2.strhash  1.07 duk.O2.master  1.26 duk.O2.130  4.18
test-string-uppercase.js        : duk.O2.strhash  2.24 duk.O2.master  2.41 duk.O2.130  2.64
test-try-catch-nothrow.js       : duk.O2.strhash  3.13 duk.O2.master  3.11 duk.O2.130  2.62
test-try-catch-throw.js         : duk.O2.strhash 41.16 duk.O2.master 40.47 duk.O2.130 39.88
test-try-finally-nothrow.js     : duk.O2.strhash  3.63 duk.O2.master  3.59 duk.O2.130  2.89
test-try-finally-throw.js       : duk.O2.strhash 49.84 duk.O2.master 50.90 duk.O2.130 48.41
```

**Comment by fatcerberus** [comment]
Hm, not as impressive as I imagined.

**Comment by fatcerberus** [comment]
I noticed in the diffs, a large block comment you deleted said that Duktape wasn't using Lua's string hashing method due to potential cache issues.  If that's no longer a problem, then has the Lua algorithm changed?

**Comment by svaarala** [comment]
Hmm, tried to reply by e-mail but it didn't appear here. Anyway, with some slight edits now that I have an actual keyboard :-)

Note that this branch only affects code doing string interning and has no impact on other tests. The string intern match case is the "purest" microbenchmark doing this, and is about 2x faster. The most relevant (= using string hashing the most) test cases are probably:

```
test-string-charlen-ascii.js    : duk.O2.strhash  1.38 duk.O2.master  1.62 duk.O2.130  5.41
test-string-charlen-nonascii.js : duk.O2.strhash  2.87 duk.O2.master  3.09 duk.O2.130  4.00
test-string-intern-match.js     : duk.O2.strhash  0.40 duk.O2.master  0.99 duk.O2.130  0.99
test-string-intern-miss.js      : duk.O2.strhash  1.37 duk.O2.master  2.04 duk.O2.130  2.58
test-string-plain-concat.js     : duk.O2.strhash  1.07 duk.O2.master  1.26 duk.O2.130  4.18
test-string-uppercase.js        : duk.O2.strhash  2.24 duk.O2.master  2.41 duk.O2.130  2.64
```

**Comment by svaarala** [comment]
Re: caching, Lua fetches one byte at a time with a potentially large skip, fetching at most ~33 bytes in total regardless of string length. That byte fetch is cache inefficient because a whole line is (potentially) fetched - but because we're talking about only 33 byte fetches in total (per string intern) this is not a big practical concern, and it's still faster than a more densely sampled hash. What would be possible, though, is to sample more than one byte per cache line which would provide more hash input with relatively little cost. It's probably not worth it though because the hash just needs to be good enough for a few internal data structures (unless one aims to provide some protection against malicious code intentionally creating a lot of collisions).

However, I'd maybe like the hash to cover the prefix and suffix of long strings better though, e.g. by including the first and last 16 bytes in the hash. This would ensure any appended or prepended counters and such would be include in full.

**Comment by svaarala** [comment]
Trying a few more hash variants (Bernstein, FNV, etc):

```
test-json-string-bench.js         : duk.O2.lua1  5.32 duk.O2.lua2  5.40 duk.O2.lua3  6.67 duk.O2.hybrid1  5.39 duk.O2.hybrid2  5.51 duk.O2.bernstein1  5.92 duk.O2.bernstein2  5.94 duk.O2.fnv1  5.98 duk.O2.oaat1  5.95 duk.O2.master  5.47 duk.O2.130  6.16
test-json-string-parse.js         : duk.O2.lua1  0.62 duk.O2.lua2  0.62 duk.O2.lua3  0.55 duk.O2.hybrid1  0.55 duk.O2.hybrid2  0.56 duk.O2.bernstein1  0.58 duk.O2.bernstein2  0.58 duk.O2.fnv1  0.59 duk.O2.oaat1  0.59 duk.O2.master  0.61 duk.O2.130  0.61
test-json-string-stringify.js     : duk.O2.lua1  1.04 duk.O2.lua2  1.01 duk.O2.lua3  1.04 duk.O2.hybrid1  1.07 duk.O2.hybrid2  1.04 duk.O2.bernstein1  1.03 duk.O2.bernstein2  1.01 duk.O2.fnv1  1.02 duk.O2.oaat1  1.04 duk.O2.master  1.08 duk.O2.130  1.31
test-regexp-string-parse.js       : duk.O2.lua1 10.72 duk.O2.lua2 10.39 duk.O2.lua3 10.51 duk.O2.hybrid1 11.36 duk.O2.hybrid2 11.35 duk.O2.bernstein1 11.40 duk.O2.bernstein2 10.34 duk.O2.fnv1 10.34 duk.O2.oaat1 10.32 duk.O2.master 10.47 duk.O2.130 10.63
test-string-array-concat.js       : duk.O2.lua1  6.42 duk.O2.lua2  6.45 duk.O2.lua3  6.55 duk.O2.hybrid1  6.33 duk.O2.hybrid2  6.40 duk.O2.bernstein1  6.41 duk.O2.bernstein2  6.36 duk.O2.fnv1  6.39 duk.O2.oaat1  6.43 duk.O2.master  6.38 duk.O2.130  6.46
test-string-charlen-ascii.js      : duk.O2.lua1  1.35 duk.O2.lua2  1.36 duk.O2.lua3  1.36 duk.O2.hybrid1  1.36 duk.O2.hybrid2  1.36 duk.O2.bernstein1  1.35 duk.O2.bernstein2  1.34 duk.O2.fnv1  1.36 duk.O2.oaat1  1.36 duk.O2.master  1.59 duk.O2.130  5.32
test-string-charlen-nonascii.js   : duk.O2.lua1  2.82 duk.O2.lua2  2.82 duk.O2.lua3  2.82 duk.O2.hybrid1  2.82 duk.O2.hybrid2  2.82 duk.O2.bernstein1  2.82 duk.O2.bernstein2  2.83 duk.O2.fnv1  2.82 duk.O2.oaat1  2.83 duk.O2.master  3.02 duk.O2.130  3.94
test-string-compare.js            : duk.O2.lua1  3.83 duk.O2.lua2  3.84 duk.O2.lua3  3.85 duk.O2.hybrid1  3.83 duk.O2.hybrid2  3.83 duk.O2.bernstein1  3.84 duk.O2.bernstein2  3.83 duk.O2.fnv1  3.82 duk.O2.oaat1  3.82 duk.O2.master  3.82 duk.O2.130  3.80
test-string-decodeuri.js          : duk.O2.lua1  3.58 duk.O2.lua2  3.60 duk.O2.lua3  3.59 duk.O2.hybrid1  3.59 duk.O2.hybrid2  3.59 duk.O2.bernstein1  3.59 duk.O2.bernstein2  3.58 duk.O2.fnv1  3.59 duk.O2.oaat1  3.59 duk.O2.master  3.60 duk.O2.130  3.60
test-string-encodeuri.js          : duk.O2.lua1  4.01 duk.O2.lua2  4.01 duk.O2.lua3  4.01 duk.O2.hybrid1  4.02 duk.O2.hybrid2  4.03 duk.O2.bernstein1  4.03 duk.O2.bernstein2  4.03 duk.O2.fnv1  4.01 duk.O2.oaat1  4.02 duk.O2.master  4.02 duk.O2.130  4.39
test-string-intern-grow.js        : duk.O2.lua1  7.05 duk.O2.lua2  7.20 duk.O2.lua3  7.22 duk.O2.hybrid1  7.01 duk.O2.hybrid2  7.14 duk.O2.bernstein1  6.76 duk.O2.bernstein2  6.84 duk.O2.fnv1  6.88 duk.O2.oaat1  7.33 duk.O2.master 18.82 duk.O2.130 18.73
test-string-intern-match-short.js : duk.O2.lua1  2.37 duk.O2.lua2  2.52 duk.O2.lua3  2.46 duk.O2.hybrid1  2.92 duk.O2.hybrid2  2.92 duk.O2.bernstein1  2.21 duk.O2.bernstein2  2.21 duk.O2.fnv1  2.26 duk.O2.oaat1  2.50 duk.O2.master  2.22 duk.O2.130  2.23
test-string-intern-match.js       : duk.O2.lua1  0.39 duk.O2.lua2  0.40 duk.O2.lua3  0.40 duk.O2.hybrid1  0.39 duk.O2.hybrid2  0.39 duk.O2.bernstein1  0.37 duk.O2.bernstein2  0.37 duk.O2.fnv1  0.38 duk.O2.oaat1  0.39 duk.O2.master  0.97 duk.O2.130  0.98
test-string-intern-miss-short.js  : duk.O2.lua1  4.87 duk.O2.lua2  5.05 duk.O2.lua3  5.06 duk.O2.hybrid1  5.68 duk.O2.hybrid2  5.65 duk.O2.bernstein1  4.69 duk.O2.bernstein2  4.79 duk.O2.fnv1  4.78 duk.O2.oaat1  5.13 duk.O2.master  4.91 duk.O2.130  5.11
test-string-intern-miss.js        : duk.O2.lua1  1.33 duk.O2.lua2  1.34 duk.O2.lua3  1.33 duk.O2.hybrid1  1.40 duk.O2.hybrid2  1.39 duk.O2.bernstein1  1.32 duk.O2.bernstein2  1.28 duk.O2.fnv1  1.32 duk.O2.oaat1  1.31 duk.O2.master  2.01 duk.O2.130  2.54
test-string-plain-concat.js       : duk.O2.lua1  1.03 duk.O2.lua2  1.02 duk.O2.lua3  1.05 duk.O2.hybrid1  1.02 duk.O2.hybrid2  1.03 duk.O2.bernstein1  1.03 duk.O2.bernstein2  1.02 duk.O2.fnv1  1.04 duk.O2.oaat1  1.05 duk.O2.master  1.22 duk.O2.130  4.14
test-string-uppercase.js          : duk.O2.lua1  2.20 duk.O2.lua2  2.32 duk.O2.lua3  2.30 duk.O2.hybrid1  2.17 duk.O2.hybrid2  2.31 duk.O2.bernstein1  2.19 duk.O2.bernstein2  2.18 duk.O2.fnv1  2.20 duk.O2.oaat1  2.20 duk.O2.master  2.31 duk.O2.130  2.56
```

Seems like Bernstein's hash (see http://eternallyconfuzzled.com/tuts/algorithms/jsw_tut_hashing.aspx) with Lua-like skipping might be the best of these. I'll need some tests that bring out the differences more reliably to be certain (the measurements are quite noisy). I'll also run the full performance test set to see what else is affected.

**Comment by svaarala** [comment]
The djb2 hash was originally posted to Usenet, and I can't find an explicit license or release to public domain. This is unlikely to be an issue: djb2 hash is part of the code base of several projects under different licenses (including MIT and GPL). Still, if anyone can point to explicit license information, that'd be nice.

**Comment by svaarala** [comment]
Some comparison between djb2 and Lua hash:

```
test-add-fastint.js             : duk.O2.bernstein1a  0.08 duk.O2.lua1  0.08 duk.O2.master  0.08
test-add-float.js               : duk.O2.bernstein1a  0.08 duk.O2.lua1  0.08 duk.O2.master  0.09
test-add-nan-fastint.js         : duk.O2.bernstein1a  0.09 duk.O2.lua1  0.09 duk.O2.master  0.09
test-add-nan.js                 : duk.O2.bernstein1a  0.08 duk.O2.lua1  0.08 duk.O2.master  0.07
test-array-read.js              : duk.O2.bernstein1a  1.84 duk.O2.lua1  1.85 duk.O2.master  1.83
test-array-write.js             : duk.O2.bernstein1a  2.71 duk.O2.lua1  2.71 duk.O2.master  2.71
test-assign-add.js              : duk.O2.bernstein1a  5.12 duk.O2.lua1  5.12 duk.O2.master  5.09
test-assign-addto-nan.js        : duk.O2.bernstein1a  1.51 duk.O2.lua1  1.52 duk.O2.master  1.50
test-assign-addto.js            : duk.O2.bernstein1a  5.13 duk.O2.lua1  5.09 duk.O2.master  5.13
test-assign-const-int.js        : duk.O2.bernstein1a  2.61 duk.O2.lua1  2.61 duk.O2.master  2.62
test-assign-const.js            : duk.O2.bernstein1a  3.80 duk.O2.lua1  3.83 duk.O2.master  3.79
test-assign-literal.js          : duk.O2.bernstein1a  4.39 duk.O2.lua1  4.42 duk.O2.master  4.41
test-assign-reg.js              : duk.O2.bernstein1a  3.12 duk.O2.lua1  3.08 duk.O2.master  3.12
test-bitwise-ops.js             : duk.O2.bernstein1a  0.73 duk.O2.lua1  0.73 duk.O2.master  0.72
test-break-fast.js              : duk.O2.bernstein1a  1.69 duk.O2.lua1  1.70 duk.O2.master  1.63
test-break-slow.js              : duk.O2.bernstein1a  7.99 duk.O2.lua1  7.92 duk.O2.master  8.06
test-buffer-nodejs-read.js      : duk.O2.bernstein1a  2.45 duk.O2.lua1  2.48 duk.O2.master  2.52
test-buffer-nodejs-write.js     : duk.O2.bernstein1a  3.30 duk.O2.lua1  3.29 duk.O2.master  3.27
test-buffer-object-read.js      : duk.O2.bernstein1a  2.47 duk.O2.lua1  2.48 duk.O2.master  2.52
test-buffer-object-write.js     : duk.O2.bernstein1a  3.30 duk.O2.lua1  3.29 duk.O2.master  3.29
test-buffer-plain-read.js       : duk.O2.bernstein1a  2.01 duk.O2.lua1  2.02 duk.O2.master  2.06
test-buffer-plain-write.js      : duk.O2.bernstein1a  1.91 duk.O2.lua1  1.92 duk.O2.master  1.94
test-call-basic-1.js            : duk.O2.bernstein1a  9.28 duk.O2.lua1  9.39 duk.O2.master  9.35
test-call-basic-2.js            : duk.O2.bernstein1a  9.26 duk.O2.lua1  9.34 duk.O2.master  9.37
test-call-basic-3.js            : duk.O2.bernstein1a 15.11 duk.O2.lua1 15.18 duk.O2.master 15.10
test-call-basic-4.js            : duk.O2.bernstein1a 37.80 duk.O2.lua1 37.93 duk.O2.master 37.37
test-call-native.js             : duk.O2.bernstein1a 15.10 duk.O2.lua1 14.87 duk.O2.master 15.21
test-compile-mandel-nofrac.js   : duk.O2.bernstein1a 13.69 duk.O2.lua1 13.70 duk.O2.master 13.70
test-compile-mandel.js          : duk.O2.bernstein1a 16.82 duk.O2.lua1 16.75 duk.O2.master 16.69
test-compile-short.js           : duk.O2.bernstein1a 10.39 duk.O2.lua1 10.35 duk.O2.master 10.15
test-continue-fast.js           : duk.O2.bernstein1a  2.26 duk.O2.lua1  2.23 duk.O2.master  2.19
test-continue-slow.js           : duk.O2.bernstein1a  8.46 duk.O2.lua1  8.39 duk.O2.master  8.58
test-empty-loop.js              : duk.O2.bernstein1a  2.51 duk.O2.lua1  2.53 duk.O2.master  2.50
test-fib.js                     : duk.O2.bernstein1a  7.91 duk.O2.lua1  8.03 duk.O2.master  8.18
test-global-lookup.js           : duk.O2.bernstein1a 10.60 duk.O2.lua1 10.63 duk.O2.master 11.78
test-hello-world.js             : duk.O2.bernstein1a  0.00 duk.O2.lua1  0.00 duk.O2.master  0.00
test-hex-decode.js              : duk.O2.bernstein1a  5.51 duk.O2.lua1  5.51 duk.O2.master  5.49
test-hex-encode.js              : duk.O2.bernstein1a 15.40 duk.O2.lua1 15.33 duk.O2.master 15.55
test-json-integer-parse.js      : duk.O2.bernstein1a  0.41 duk.O2.lua1  0.42 duk.O2.master  0.42
test-json-number-parse.js       : duk.O2.bernstein1a  5.36 duk.O2.lua1  5.39 duk.O2.master  5.30
test-json-serialize.js          : duk.O2.bernstein1a  1.56 duk.O2.lua1  1.56 duk.O2.master  1.53
test-json-string-bench.js       : duk.O2.bernstein1a  5.48 duk.O2.lua1  5.50 duk.O2.master  5.53
test-json-string-parse.js       : duk.O2.bernstein1a  0.57 duk.O2.lua1  0.56 duk.O2.master  0.60
test-json-string-stringify.js   : duk.O2.bernstein1a  0.99 duk.O2.lua1  0.99 duk.O2.master  1.03
test-mandel.js                  : duk.O2.bernstein1a  4.66 duk.O2.lua1  4.65 duk.O2.master  4.67
test-prop-read.js               : duk.O2.bernstein1a  4.88 duk.O2.lua1  4.91 duk.O2.master  5.05
test-prop-write.js              : duk.O2.bernstein1a  4.57 duk.O2.lua1  4.56 duk.O2.master  4.49
test-reg-readwrite-object.js    : duk.O2.bernstein1a  3.28 duk.O2.lua1  3.28 duk.O2.master  3.26
test-reg-readwrite-plain.js     : duk.O2.bernstein1a  2.19 duk.O2.lua1  2.19 duk.O2.master  2.20
test-regexp-string-parse.js     : duk.O2.bernstein1a 10.62 duk.O2.lua1 10.52 duk.O2.master 10.72
test-string-array-concat.js     : duk.O2.bernstein1a  6.55 duk.O2.lua1  6.64 duk.O2.master  6.53
test-string-charlen-ascii.js    : duk.O2.bernstein1a  1.40 duk.O2.lua1  1.39 duk.O2.master  1.61
test-string-charlen-nonascii.js : duk.O2.bernstein1a  2.87 duk.O2.lua1  2.88 duk.O2.master  3.06
test-string-compare.js          : duk.O2.bernstein1a  3.92 duk.O2.lua1  3.92 duk.O2.master  3.92
test-string-decodeuri.js        : duk.O2.bernstein1a  3.68 duk.O2.lua1  3.68 duk.O2.master  3.67
test-string-encodeuri.js        : duk.O2.bernstein1a  4.13 duk.O2.lua1  4.09 duk.O2.master  4.12
test-string-intern-grow.js      : duk.O2.bernstein1a  6.89 duk.O2.lua1  7.22 duk.O2.master 19.21
test-string-intern-match-short.js: duk.O2.bernstein1a  2.29 duk.O2.lua1  2.41 duk.O2.master  2.29
test-string-intern-match.js     : duk.O2.bernstein1a  0.38 duk.O2.lua1  0.40 duk.O2.master  0.98
test-string-intern-miss-short.js: duk.O2.bernstein1a  4.79 duk.O2.lua1  4.98 duk.O2.master  5.02
test-string-intern-miss.js      : duk.O2.bernstein1a  1.35 duk.O2.lua1  1.36 duk.O2.master  2.04
test-string-plain-concat.js     : duk.O2.bernstein1a  1.05 duk.O2.lua1  1.08 duk.O2.master  1.27
test-string-uppercase.js        : duk.O2.bernstein1a  2.24 duk.O2.lua1  2.25 duk.O2.master  2.44
test-try-catch-nothrow.js       : duk.O2.bernstein1a  3.11 duk.O2.lua1  3.13 duk.O2.master  3.12
test-try-catch-throw.js         : duk.O2.bernstein1a 40.93 duk.O2.lua1 42.05 duk.O2.master 41.64
test-try-finally-nothrow.js     : duk.O2.bernstein1a  3.66 duk.O2.lua1  3.65 duk.O2.master  3.63
test-try-finally-throw.js       : duk.O2.bernstein1a 51.82 duk.O2.lua1 51.93 duk.O2.master 51.89
```

**Comment by svaarala** [comment]
This test in particular looks nice:

```
test-string-intern-grow.js      : duk.O2.bernstein1a  6.89 duk.O2.lua1  7.22 duk.O2.master 19.21
```

The test is about interning a 1000 strings, releasing them, and interning them again, exercising string hashing, character length computation, and string table insert/remove behavior. Master already includes the string length computation optimization (which is not a significant part of this test).

**Comment by svaarala** [comment]
Retesting and adding a few more tests illustrates the difference in the string hash "quality" and how it affects string table behavior. As background, the Lua string hash function starts from the end of string and works its way backwards towards the beginning. When the string is at most 31 bytes long, all bytes will be sampled with the *first* byte being added to the hash last. As a result the first byte will also have the least time to avalanche across the hash result. For strings >= 32 bytes long the offset stride is `(len >> 5) + 1`, i.e. 2 for length 32, 3 for length 64, etc.

First, the original test with 2048 byte inputs where a 3-byte counter is placed in offsets 0, 1, 2, lowest byte first. This is a worst case for the Lua-like construction because changes in offset 0 won't affect a big portion of the hash (being the last byte added to the hash). With a 2048-byte input the skipping factor is rather large (65 bytes between hashed bytes) so that the counter is actually not included in the hash at all.

As a result, this performs much worse with the Lua-like hash compared to the slower but more dense hash in master (this is essentially the worst case because all 1000 strings will have the same hash value):

```
test-string-intern-grow.js      : duk.O2.bernstein1a 38.67 duk.O2.lua1 40.95 duk.O2.master  3.99
```

Note that this is just a microbenchmark illustrating the tradeoff between fast string computation and hash quality which affects the tendency for string hashes to cluster in string table or object property tables. This doesn't mean changing to a Lua-like hash is a bad idea though, it's just good to know there is a tradeoff involved; in master string hashing is ~100% slower but because the hashes are better the string table portion performs better.

Given that Duktape needs to sample every byte to compute the string UTF-8 length, it might be sensible to have a *fully dense* string hash option (or perhaps just the hash in master) for applications where clustering caused by especially crated inputs might be an issue.

I also added a test with a 31-byte input string (which is fully dense), with the counter either at the beginning (`...-short.js`) or end (`...-short2.js`). The latter works better with a Lua-like hash because the counter has time to propagate across the hash value, this is also visible in the test result:

```
test-string-intern-grow-short.js: duk.O2.bernstein1a 22.04 duk.O2.lua1 17.35 duk.O2.master  7.47
test-string-intern-grow-short2.js: duk.O2.bernstein1a  7.58 duk.O2.lua1  8.17 duk.O2.master  7.37
```

The reverse hashing direction means counters or changing values at the end of the string work better than those at the beginning. This sounds like a sensible default.

**Comment by svaarala** [comment]
For comparison, here's the 2048-byte intern test with the least significant byte of the counter at the end of the string so that the LSB gets included in the hash (but only 256 different hashes are produced because other bytes of the counter are not included):

```
$ time ./duk.O2.master tests/perf/test-string-intern-grow2.js 
real	0m4.352s
user	0m4.176s
sys	0m0.152s

$ time ./duk.O2.bernstein1a tests/perf/test-string-intern-grow2.js 
real	0m3.575s
user	0m3.423s
sys	0m0.104s

$ time ./duk.O2.lua1 tests/perf/test-string-intern-grow2.js 
real	0m3.585s
user	0m3.451s
sys	0m0.112s
```

In this case the Lua/Bernstein hash with skipping performs better than master; the small clustering (around 3-4 bytes per hash value) is offset by faster hashing.

**Comment by fatcerberus** [comment]
I guess in the end it's a matter of figuring out which case better represents real-world usage: If it turns out to be common to have a lot of very similar strings in flight, the dense hash might be better, otherwise the sparse hash is probably the clear winner.

**Comment by svaarala** [comment]
I'm inclined to believe the skipping approach of Lua is good enough for most applications.

For the few applications where the difference matters it would probably nice to be able to either (a) increase the string hash density by tweaking the shift count for the stride calculation, (b) revert to the current algorithm in master, or even (c) revert to hashing the entire string (with either Murmurhash2 or Shift-add-XOR/djb2). Hopefully one would only need to do this when encountering actual issues.

**Pull request merged**
