### PR TITLE
Add initial draft of API design guidelines document

### PR DESCRIPTION
**Pull request by svaarala**
Just a quick draft of some trade-offs involves in API design and how they've been solved at the moment. The intent is to make it easier to recall current conventions when adding new calls.

### CODE REVIEW

**Comment by svaarala** [comment]
@fatcerberus This is not intended to be complete by any means. Within the scope of this pull, I'd like to at least add some placeholder sections for issues that may be relevant to document however, so suggestions welcome!

**Comment by svaarala** [comment]
Couple of issues that come to mind:

- Argument naming
- Argument typing
- Varargs API calls; when provided

**Comment by fatcerberus** [comment]
Regarding the flags vs. multiple calls debate: For me this decision usually comes down to - What would a combined API call (with flags) look like internally?

If you have function with a large switch statement or if/else tower switching on the flags with little to nothing in common between the cases, that almost certainly would do well to be split up; each function should only do one basic thing.

Where flags make more sense is in the case of calls that *already* do only one basic thing (e.g. `duk_pcompile()`) and have only subtle variations in the code paths given different flags.  For instance you can compile source code as either strict or non-strict, but the compiler does mostly the same thing in either case.

**Comment by svaarala** [comment]
> This seems easy enough to avoid: Simply wrap the macro body in a do { ... } while (0); and assign flags to a local variable. C has block scope so there should be no issue there.

Unfortunately that doesn't work for expressions which must evaluate to a value.

**Comment by svaarala** [comment]
> Regarding the flags vs. multiple calls debate: For me this decision usually comes down to - What would a combined API call (with flags) look like internally?

I view this quite differently: often a public API outlives the internal implementation, sometimes several times. So what's crucial is that the public API is conceptually good, and that it can be mapped to different internal implementations over time.

**Comment by fatcerberus** [comment]
Sorry, lapsed into "developer mode" there - despite speaking in concrete terms, I really meant that from a conceptual standpoint: if a call can do 3 totally different things depending on what flags you pass to it, maybe you shouldn't be using flags in that call. :)

**Comment by svaarala** [comment]
Sure, agree with that. I don't think that has been a concrete issue though :)

**Pull request merged**
