### PR TITLE
Fix compile warnings for lazy charlen

### PR DESCRIPTION
**Pull request by svaarala**
Fix some compile warnings caused by lazy charlen change.

### CODE REVIEW

**Comment by svaarala** [comment]
@fatcerberus Could you check if this fixes the warnings you saw in master? The Appveyor queue isn't progressing and I don't have a Windows VM handy right now :-/.

**Comment by fatcerberus** [comment]
Sure, I'll test in a bit.

**Comment by fatcerberus** [comment]
No more warnings at `/W3`, so the issue here is fixed.  However using `/W4` I found the following:
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4244	'=': conversion from 'duk_bool_t' to 'duk_uint8_t', possible loss of data (compiling source file ..\src\shared\duktape.c)	miniSphere	D:\src\minisphere\msvs\duk_bi_encoding.c	464	
Warning	C4244	'=': conversion from 'duk_bool_t' to 'duk_uint8_t', possible loss of data (compiling source file ..\src\shared\duktape.c)	miniSphere	D:\src\minisphere\msvs\duk_bi_encoding.c	465	
Warning	C4701	potentially uninitialized local variable 'level' used	miniSphere	d:\src\minisphere\msvs\duk_debugger.c	1520	
Warning	C4389	'!=': signed/unsigned mismatch (compiling source file ..\src\shared\duktape.c)	miniSphere	D:\src\minisphere\msvs\duk_hobject_props.c	5666	
Warning	C4245	'function': conversion from 'int' to 'duk_uint32_t', signed/unsigned mismatch (compiling source file ..\src\shared\duktape.c)	miniSphere	D:\src\minisphere\msvs\duk_hthread_builtins.c	237	
Warning	C4244	'=': conversion from 'duk_bool_t' to 'duk_uint8_t', possible loss of data (compiling source file ..\src\shared\duktape.c)	miniSphere	D:\src\minisphere\msvs\duk_js_compiler.c	7783	
Warning	C4244	'=': conversion from 'duk_bool_t' to 'duk_uint8_t', possible loss of data (compiling source file ..\src\shared\duktape.c)	miniSphere	D:\src\minisphere\msvs\duk_js_compiler.c	7798	
Warning	C4701	potentially uninitialized local variable 'd3' used	miniSphere	d:\src\minisphere\msvs\duk_js_compiler.c	2265	
```

**Comment by svaarala** [comment]
Last we tried /W4 clean compile wasn't easily possible, but I'll check out the ones above now.

**Comment by svaarala** [comment]
Warnings seem harmless. MSVC control flow analysis doesn't seem able to correlate paths such as:

```
/* bar uninitialized */
if (foo) {
    bar = 1;
}
...
if (foo) {
    /* use bar */
}
```

This causes "bar uninitialized" warnings even if foo cannot change in between. This was the case in the debugger code for example; harmless warning in practice.

**Comment by svaarala** [comment]
Ok, those warnings may now be fixed. I had to change `duk_propdesc.flags` to unsigned so there may be some knock-off warnings from that (nothing on Linux targets though).

**Comment by fatcerberus** [comment]
> Last we tried /W4 clean compile wasn't easily possible

I know, that's why I left out all the "unreachable code" warnings. :)  It was mainly the signed/unsigned mismatch ones that concerned me.

**Comment by fatcerberus** [comment]
The only warnings left for `/W4` are a bunch of unreachable code warnings, it seems.  You even managed to squash the "potentially uninitialized variable" ones.  IIRC, those weren't easily fixable the last time I reported them.

Those only thing else that jumps out at me are these:
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4127	conditional expression is constant (compiling source file ..\src\shared\duktape.c)	miniSphere	D:\src\minisphere\msvs\duk_heap_alloc.c	746	
Warning	C4127	conditional expression is constant (compiling source file ..\src\shared\duktape.c)	miniSphere	D:\src\minisphere\msvs\duk_api_stack.c	4374	
```

Those seem to be `sizeof` comparisons, so probably not easily fixable.

**Comment by svaarala** [comment]
Ok, so I guess this is merge ready :)

**Comment by fatcerberus** [comment]
Thanks, now I can have a clean build again. :)

**Pull request merged**
