### PR TITLE
Fix some MSVC /W4 cast warnings

### PR DESCRIPTION
**Pull request by svaarala**
https://github.com/svaarala/duktape/issues/306#issuecomment-168883454

### CODE REVIEW

**Comment by fatcerberus** [comment]
Going to test this now, I'll let you know what happens. :)

**Comment by svaarala** [comment]
Thanks :)

**Comment by fatcerberus** [comment]
Yep, that only warning left is:

```
1>duk_api_stack.c(3948): warning C4127: conditional expression is constant
```

I'm impressed.  Most people ignore `/W4` completely because it generates a lot of spurious warnings, but you went the extra mile anyway.  Good work as always!

**Comment by fatcerberus** [comment]
I forgot I have LTCG (i.e. full-program optimization) on, it turns out a bunch more warnings are generated at link time.  Almost every single one is for "unreachable code", but there's one that sticks out:

```
1>d:\src\minisphere\msvc\duk_js_compiler.c(2188): warning C4701: potentially uninitialized local variable 'd3' used
```

**Comment by svaarala** [comment]
Hmm, that uninitialized case should never occur: `d3` is only referenced if `accept != 0` and the switch-case ensures `d3` is set or `accept` is set to 0. But I'll see if I can restructure it.

**Comment by fatcerberus** [comment]
I've noticed similar issues with MSVC's static analyzer where it claims a variable is uninitialized when it really isn't.  Just figured I'd point it out anyway. :)

**Comment by fatcerberus** [comment]
Regarding the lightfunc varargs fix: Could that have potentially caused issues in practice?  You seem to have given it special attention.

**Comment by svaarala** [comment]
At first I thought it might have caused a bug but it didn't - it got cast from `duk_idx_t` to `duk_uint16_t`, and then into `duk_int16_t`, so that the varargs marker (-1) ended up correct.

**Comment by fatcerberus** [comment]
Did you figure out what to do (if anything) about the `d3` uninitialized var warning?

**Comment by svaarala** [comment]
I got lazy and decided to change it later. It'd be trivial for example to just initialize d3 to `0.0` but that generates dead code which would be nice to avoid. I'll look into it in master after 1.4.0 release.

**Pull request merged**
