### PR TITLE
Use _snprintf() for pre-MSVC 2015 in extras/module-duktape

### LINKED ISSUE #1369: Module loader gives a warning on Windows (Visual Studio 2013)
To be precise, compiling duk_module_duktape.c gives the following warning:

`warning C4013: 'snprintf' undefined; assuming extern returning int`

The problem occurs because Microsoft prepends the names of certain functions with an underscore. My current fix is adding the following to duk_module_duktape.h:

```
#ifdef _WIN32
	#define snprintf _snprintf
#endif
```

### PR DESCRIPTION
**Pull request by svaarala**
Fixes #1369.

### CODE REVIEW

**Comment by svaarala** [comment]
@armornick Could you verify if this fixes the warning for you (I don't have a Windows installation right now and Appveyor is not processing its job queue for some reason so I can't easily test right now).

**Comment by seanmiddleditch** [comment]
You might consider using [stbsp_snprintf](https://github.com/nothings/stb/blob/master/stb_sprintf.h) instead. Common behavior across all platforms _and_ it's quite a bit faster (see the benchmark results in the header's comments).

**Comment by svaarala** [comment]
That wouldn't necessarily be appropriate for low memory targets where there's often a platform-provided (or otherwise preferred) sprintf() provider and another one would be unnecessary footprint. Proper sprintf() footprint isn't negligible because of floating point formatting.

**Comment by svaarala** [comment]
@armornick I'll merge this now - please comment if the fix doesn't work for you.

**Pull request merged**
