### PR TITLE
Genconfig modular duk_config.h generation

### LINKED ISSUE #453: Solaris endian detection fix
The original fix is in duktape.rb: https://github.com/judofyr/duktape.rb/pull/33

### PR DESCRIPTION
**Pull request by svaarala**
Genconfig improvements:

- Generate both the autodetect (default) duk_config.h and target specific duk_config.h from same modular header snippets.
- Generate feature option support automatically (previously DUK_OPT_xxx handling needed manual work).
- Refactor header snippets so that most platform, compiler, and architecture tweaks are in their respective files.
- Minor compilation fixes.
- Fixes #453.

Tasks:

- [x] Verify Solaris fix (swapped compiler and platform byte order detection blocks), apply original fix?
- [x] Test autogenerated duk_config.h as widely as possible

Because a lot of header snippets and genconfig trivia was shuffled around, it's important to test well before merging to master.  Testing status:

- [x] Linux gcc x86
- [x] Linux gcc x64
- [x] Linux gcc x32
- [x] Linux gcc ARM 32-bit
- [x] Linux gcc MIPS 32-bit
- [x] Linux gcc SuperH 32-bit
- [x] Linux g++ x86
- [x] Linux g++ x64
- [x] Linux g++ x32
- [x] Linux g++ ARM 32-bit
- [x] Linux g++ MIPS 32-bit
- [x] Linux g++ SuperH 32-bit
- [x] Linux TinyC 64-bit
- [x] Linux clang x86
- [x] Linux clang x64
- [x] Linux clang x32
- [x] Windows MSVC x86
- [x] Windows MSVC x64
- [x] Windows Mingw x86
- [x] Windows Mingw x64 => skipped
- [x] OSX clang x86
- [x] OSX clang x64
- [x] AmigaOS m68k vbcc
- [x] AmigaOS m68k gcc => skipped
- [x] AmigaOS PPC32 gcc
- [x] RiscOS ARM32 gcc

For each platform:

- Test single source build, C99 and non-C99, C++11 and non-C++11
- Test separate sources build, C99 and non-C99, C++11 and non-C++11
- For Windows, test DLL build

Other tests:

- [x] Test Solaris/illumos issue (#453) by simulating the root cause on Linux (`#define _BIG_ENDIAN` with an empty value) => build fails in master, works in this branch so probably fixed

Known issues (already in master):

- When compiling using g++ or mingw from separate sources: "warning: 'visibility' attribute ignored".
- When compiling in explicit C89 mode (gcc): "warning: implicit declaration of function 'snprintf'", snprintf() is not part of C89.
- MinGW 64-bit: "duk_js_call.c:844 idx_func may be clobbered by longjmp or fork"

### CODE REVIEW

**Comment by svaarala** [comment]
Prebuilt dist snapshot: http://duktape.org/snapshots/duktape-1.3.99-20151209151055-v1.3.0-383-gb7b1c5f-duk-config-improvements.tar.xz

**Comment by fatcerberus** [comment]
Hm, since this merge minisphere has stopped generating Throw notifys.  Any idea what happened?

**Comment by svaarala** [comment]
`DUK_USE_DEBUGGER_THROW_NOTIFY` was changed to false by default. I can change it back, it was changed for a technical issue: throw notify "requires" `DUK_USE_DEBUGGER_SUPPORT` which is not enabled by default so the default config would be inconsistent. But I could remove that "requires" metadata, since it's not really required, the option is just ignored unless debugger support is enabled.

**Comment by svaarala** [comment]
Should be fixed by #494.

**Pull request merged**
