### PR TITLE
Use a 32-bit refcount field by default

### LINKED ISSUE #1399: Using a 32-bit refcount for duk_heaphdr h_refcount field
I noticed the following comment in `duk_heaphdr.h`, explaining why `h_refcount` is declared as a `duk_size_t` instead of `duk_uint32_t`:

> Technically, 'h_refcount' must be wide enough to guarantee that it cannot wrap (otherwise objects might be freed incorrectly after wrapping).  This means essentially that the refcount field must be as wide as data pointers.  On 64-bit platforms this means that the refcount needs to be 64 bits even if an 'int' is 32 bits.  This is a bit unfortunate, and compromising on this might be reasonable in the future.

Would you consider a duk_config option to use `duk_uint32_t` for `h_refcount`?  The default behavior could be to use `duk_size_t`, but if the client knows they'll never have that many references to an object, they could opt into saving 8 bytes per `duk_heaphdr`.

### PR DESCRIPTION
**Pull request by svaarala**
Fixes #1399.

### CODE REVIEW

**Comment by svaarala** [comment]
Hello world massif output from before (x64, default options):

```
    KB
135.3^                                                              :::       
     |                                                      :::: #:::  :      
     |                                         :: @:::::::@::: ::#:::  :::::@ 
     |                                   @  :  : :@: :::: @::: ::#:::  :    @ 
     |                                  @@:::::: :@: :::: @::: ::#:::  :    @ 
     |                                 @@@: :: : :@: :::: @::: ::#:::  :    @ 
     |                               ::@@@: :: : :@: :::: @::: ::#:::  :    @ 
     |                            @@@::@@@: :: : :@: :::: @::: ::#:::  :    @ 
     |                           @@@ ::@@@: :: : :@: :::: @::: ::#:::  :    @ 
     |                        @@@@@@ ::@@@: :: : :@: :::: @::: ::#:::  :    @:
     |                       :@@ @@@ ::@@@: :: : :@: :::: @::: ::#:::  :    @:
     |                     @@:@@ @@@ ::@@@: :: : :@: :::: @::: ::#:::  :    @:
     |                   @:@ :@@ @@@ ::@@@: :: : :@: :::: @::: ::#:::  :    @:
     |                  :@:@ :@@ @@@ ::@@@: :: : :@: :::: @::: ::#:::  :    @:
     |                :::@:@ :@@ @@@ ::@@@: :: : :@: :::: @::: ::#:::  :    @:
     |              ::: :@:@ :@@ @@@ ::@@@: :: : :@: :::: @::: ::#:::  :    @:
     |            @@: : :@:@ :@@ @@@ ::@@@: :: : :@: :::: @::: ::#:::  :    @:
     |           @@ : : :@:@ :@@ @@@ ::@@@: :: : :@: :::: @::: ::#:::  :    @:
     |           @@ : : :@:@ :@@ @@@ ::@@@: :: : :@: :::: @::: ::#:::  :    @:
     |         ::@@ : : :@:@ :@@ @@@ ::@@@: :: : :@: :::: @::: ::#:::  :    @:
   0 +----------------------------------------------------------------------->Mi
     0                                                                   3.862
```

And after:

```
    KB
132.0^                                                            :           
     |                                                      @::@:#::::::      
     |                                            @:@:::::@:@::@:#:::: :::::@ 
     |                                   @ :: @:::@:@:::::@:@::@:#:::: :    @ 
     |                                  @@::::@:::@:@:::::@:@::@:#:::: :    @ 
     |                                @@@@::::@:::@:@:::::@:@::@:#:::: :    @ 
     |                              @:@@@@::::@:::@:@:::::@:@::@:#:::: :    @ 
     |                            @:@:@@@@::::@:::@:@:::::@:@::@:#:::: :    @ 
     |                          @@@:@:@@@@::::@:::@:@:::::@:@::@:#:::: :    @ 
     |                        ::@@@:@:@@@@::::@:::@:@:::::@:@::@:#:::: :    @:
     |                       :::@@@:@:@@@@::::@:::@:@:::::@:@::@:#:::: :    @:
     |                     @@:::@@@:@:@@@@::::@:::@:@:::::@:@::@:#:::: :    @:
     |                   @:@@:::@@@:@:@@@@::::@:::@:@:::::@:@::@:#:::: :    @:
     |                 @:@:@@:::@@@:@:@@@@::::@:::@:@:::::@:@::@:#:::: :    @:
     |               @:@:@:@@:::@@@:@:@@@@::::@:::@:@:::::@:@::@:#:::: :    @:
     |             @:@:@:@:@@:::@@@:@:@@@@::::@:::@:@:::::@:@::@:#:::: :    @:
     |            :@:@:@:@:@@:::@@@:@:@@@@::::@:::@:@:::::@:@::@:#:::: :    @:
     |           @:@:@:@:@:@@:::@@@:@:@@@@::::@:::@:@:::::@:@::@:#:::: :    @:
     |          :@:@:@:@:@:@@:::@@@:@:@@@@::::@:::@:@:::::@:@::@:#:::: :    @:
     |          :@:@:@:@:@:@@:::@@@:@:@@@@::::@:::@:@:::::@:@::@:#:::: :    @:
   0 +----------------------------------------------------------------------->Mi
     0                                                                   3.849
```

Peak difference is 3.3kB or about 2-3%.

**Comment by svaarala** [comment]
Object size changes on x64; before change:

```
D0 duk_heap_alloc.c:573 (duk__dump_type_sizes): duk_heaphdr=32
D0 duk_heap_alloc.c:574 (duk__dump_type_sizes): duk_heaphdr_string=24
D0 duk_heap_alloc.c:575 (duk__dump_type_sizes): duk_hstring=40
D0 duk_heap_alloc.c:576 (duk__dump_type_sizes): duk_hstring_external=48
D0 duk_heap_alloc.c:577 (duk__dump_type_sizes): duk_hobject=64
D0 duk_heap_alloc.c:578 (duk__dump_type_sizes): duk_harray=72
[...]
```

After change:

```
D0 duk_heap_alloc.c:573 (duk__dump_type_sizes): duk_heaphdr=24
D0 duk_heap_alloc.c:574 (duk__dump_type_sizes): duk_heaphdr_string=16
D0 duk_heap_alloc.c:575 (duk__dump_type_sizes): duk_hstring=32
D0 duk_heap_alloc.c:576 (duk__dump_type_sizes): duk_hstring_external=40
D0 duk_heap_alloc.c:577 (duk__dump_type_sizes): duk_hobject=56
D0 duk_heap_alloc.c:578 (duk__dump_type_sizes): duk_harray=64
[...]
```

32-bit systems are not affected.

**Comment by fatcerberus** [comment]
Not sure I understand how this saves 8 bytes per object instead of 4.  Does each heap object store two refcounts?

**Comment by svaarala** [comment]
It removes 4 bytes of padding as well as saving 4 bytes.

**Comment by fatcerberus** [comment]
Ah, thanks.  I was confused, now I'm not :)

**Comment by svaarala** [comment]
Quite interestingly there's a footprint improvement of ~0.5kB for x64 minsize and ~1.5kB x64 "make duk" too. That's a bit larger than I would have expected on x64 but apparently the small differences add up.

**Comment by svaarala** [comment]
Let's see how Octane score is affected.

**Comment by svaarala** [comment]
Ok, Octane score doesn't seem affected one way or another - so should be good to go.

**Pull request merged**
