### PR TITLE
Add vcpkg installation instructions

### PR DESCRIPTION
**Pull request by NancyLi1013**
`duktape` is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for `duktape`  and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build `duktape`, ready to be included in their projects.

We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64) to keep a wide coverage for users.

I'm a maintainer for vcpkg, and [here is what the port script looks like](https://github.com/microsoft/vcpkg/blob/master/ports/duktape/portfile.cmake). We try to keep the library maintained as close as possible to the original library.

### CODE REVIEW

**Comment by svaarala** [comment]
Thanks! Could you add yourself to the first list in AUTHORS.rst?

**Comment by svaarala** [comment]
There seem to be conflicts that need resolution, please rebase to master.

**Comment by NancyLi1013** [comment]
@svaarala 
Thanks for your review and kindly reminder.

**Comment by svaarala** [comment]
Thanks! :+1:

**Pull request merged**
