### PR TITLE
Add some benchmarking notes

### PR DESCRIPTION
**Pull request by svaarala**
Add some rough notes on benchmarking tips.

### CODE REVIEW

**Comment by fatcerberus** [comment]
Regarding functions not being collected by refcounting, would it be possible to add a special case to detect the loop (since the exact properties involved in the loop are known), and free the function anyway?  I do something similar in minisphere when freeing socket objects to detect if the socket is piped into itself (an echo server), and if so, free it at refcount = 1.

**Comment by fatcerberus** [comment]
I guess it's not a huge issue though because an emergency GC would free it anyway.

**Comment by svaarala** [comment]
Some kind of special case hack would be possible, but not sure if worth it.

The main change I'm planning to do is to make the default prototype object virtual, so that it only gets created if you actually access `.prototype` (which user code doesn't do at all for most functions). This avoids the reference loop for most functions and also reduces memory usage in general.

**Comment by fatcerberus** [comment]
Yeah, like I said the emergency garbage collector will get it anyway if needed, so it's not really an issue in practice.  Just a random thought that occurred to me.

**Comment by svaarala** [comment]
Yeah, it's not an issue when a pool allocator is used. When a pool allocator is not used, that memory won't be available for other processes in the system, and if *they* run out of memory they can't cause an emergency GC to free up the memory tied up in circular references. For some low memory targets this might be an issue (similarly for any other garbage in reference loops). In practice very low memory targets tend to use pool allocators anyway so it's not really an issue for them.

In any case, memory churn would be reduced if the reference loop was broken by default.

**Pull request merged**
