### PR TITLE
Add string.prototype.includes()

### PR DESCRIPTION
**Pull request by svaarala**
Add support for String.prototype.includes():

- [x] Rebase after #1324 is merged
- [x] Add the binding
- [x] Testcase coverage
- [x] Releases entry

### CODE REVIEW

**Comment by fatcerberus** [comment]
Can this share code with `String.prototype.indexOf()`?

**Comment by svaarala** [comment]
I didn't do any real implementation work yet, but it should be able to do that. The argument check / coercion behavior is slightly different, but a shared helper for the main scanning operation could (and should) be shared. I'll finish startsWith() and endsWith() first and then look into this one.

**Comment by svaarala** [comment]
The return value convention also differs (1/-1 vs. true/false).

**Comment by svaarala** [comment]
That search helper doesn't also perform well now (it's size optimized), and I'll maybe improve it in a separate pull. Basically the forward/backward scan modes should be outside the loop (which is pretty obvious for performance), and the `.includes()` variant doesn't need to track the character position at all.

**Comment by svaarala** [comment]
Also the pointer limit checks can be optimized differently depending on scan direction. But, separate pull.

**Pull request merged**
