### PR TITLE
Add an optional 128kB lookup to optimize regexp canonicalization

### PR DESCRIPTION
**Pull request by svaarala**
In Duktape 1.3.0 and prior case-insensitive RegExps with large unicode ranges have serious performance issues. Example regexp:

```js
var re = /[\u0000-\uffff]/i;
```

This is most likely the root cause behind this Netsurf issue (and at least another similar one):

- http://bugs.netsurf-browser.org/mantis/view.php?id=2366

The performance issue is caused by two algorithms interacting (neither alone would be a major issue):

- A continuous Unicode range may be split into multiple discontinuous ranges when it is canonicalized, so it's not enough to canonicalize the endpoints. The current simple approach is to run through the range codepoints, normalize each, and then detect the canonicalized ranges from the conversion output. This is a loop of ~64k canonicalizations for each `[\u0000-\uffff]` range in the case insensitive regexp source.
- Each canonicalization in turn runs through the size-optimized bit-packed Unicode data which doesn't have an index, so potentially hundreds of ranges are scanned. This exacerbates the problem quite a bit.

This branch has a very simple fix where a 65536-entry lookup table is used for the canonicalization operation, which should fix the immedate issue for environments where this is a practical issue:

```
$ time ./duk.O2.130 tests/perf/test-regexp-case-insensitive.js

real	0m23.962s
user	0m23.918s
sys	0m0.003s

$ time ./duk.O2 tests/perf/test-regexp-case-insensitive.js

real	0m0.019s
user	0m0.018s
sys	0m0.003s
```

This is a short term solution and the lookup table won't be enabled by default because the footprint impact is quite large.

A proper medium term solution is to use a better algorithm for handling case-insensitive RegExp ranges, and to make the Unicode data indexed and faster to work with for non-low-memory targets. It should be possible to get a similar improvement with much, much smaller footprint impact.

Partially addresses #334. The workaround is enabled using `DUK_OPT_REGEXP_CANON_WORKAROUND` (or `DUK_USE_REGEXP_CANON_WORKAROUND` if editing `duk_config.h` directly).

Tasks:

- [x] Add a config option, disabled by default
- [x] Ensure the change fixes the original Netsurf issue (also validates that root cause is understood)
- [x] Try to find a better short term solution without reworking the Unicode tables yet => future work
- [x] Resolve FIXMEs
- [x] Releases entry
- [x] Test manually without canonicalization fast path
- [x] Test manually with canonicalization fast path
- [x] Assert run with fast path
- [x] Assert run without fast path

### CODE REVIEW

**Comment by fatcerberus** [comment]
Footprint impact is what, around 256kb? Not an issue for PC platforms but definitely impractical for embedded targets.

That speedup is crazy though, almost 24s down to less than a second.

**Comment by svaarala** [comment]
The footprint impact is 64k entries of 16-bit codepoints -> 128kB.

**Comment by fatcerberus** [comment]
Oh, I was thinking of the full Unicode range which is 32-bit, I forgot Duktape only supports the BMP(?).

**Comment by svaarala** [comment]
Duktape strings support codepoints above BMP which is non-standard: individual codepoints in the string can be up to 31 bits (or so). Ecmascript strings only support 16-bit codepoints so surrogate pairs are normally used.

E5.1 treats strings as 16-bit codepoint sequences only, and doesn't support non-BMP codepoints through surrogate pairs in most operations. So for compliance, 16-bit support is enough for E5.1.

Non-BMP support is necessarily out-of-specification, so the support doesn't need to be 100%. It's fairly complete though, but for this RegExp case normalization process only the BMP is supported because the current small-but-slow algorithm would need to loop through over a million codepoints instead of just 65536 :-)

If the algorithm gets better, there should be no problem supporting codepoints above BMP for case-insensitive RegExps too -- but that's out-of-specification functionality anyway so it's not a compliance issue.

**Comment by fatcerberus** [comment]
I just noticed `duktape.c` recently ballooned from ~3MB to around 3.5MB... is that due to this change?

**Comment by svaarala** [comment]
Yes, it's the 64k entry lookup.

**Pull request merged**
