### PR TITLE
Added 'Harold Brenes' to AUTHORS.rst

### PR DESCRIPTION
**Pull request by harold-b**
As per [wiki-pr #134](https://github.com/svaarala/duktape-wiki/pull/134#issuecomment-240691723)

### CODE REVIEW

**Comment by svaarala** [comment]
@harold-b This has conflicts, please update your master and rebase to master.

**Comment by harold-b** [comment]
Strange, I synced with upstream before I made the branch... I'll see what I messed up.

**Comment by harold-b** [comment]
@svaarala ... I completely forgot to merge before I fetched ...
Should be good now.

**Comment by svaarala** [comment]
You should be on the first list (for code, documentation, etc), not the second :)

**Comment by harold-b** [comment]
Alrighty I'll fix it :)

**Comment by svaarala** [comment]
Thanks, merged.

**Pull request merged**
