### PR TITLE
Fix temporary register handling for object literal getters/setters

### PR DESCRIPTION
**Pull request by svaarala**
See bug description in https://github.com/svaarala/duktape/pull/1190#issuecomment-267533606. This was introduced by #1190 and is not present in the 1.x release.

### CODE REVIEW

**Comment by svaarala** [comment]
@fatcerberus If you have time, it'd be good to test this fixes your Minisphere issue and that no other issues surface.

**Comment by fatcerberus** [comment]
I can't test until I get home tonight but I'll be sure to let you know.

**Comment by svaarala** [comment]
Sure, no hurry :)

**Comment by svaarala** [comment]
@fatcerberus The reverted assert (and associated assignment change) is pushed and assertion test runs pass so this should be ready to merge, assuming there are no regressions left.

**Comment by fatcerberus** [comment]
Thanks, I'll test it very shortly :)

**Comment by svaarala** [comment]
Good catch by the way. This was quite an interesting bug in that it wasn't detected by other regression tests which seems intuitively unlikely given how it should manifest every time a setter/getter is created after a preceding data property.

**Comment by fatcerberus** [comment]
Yep, one of the benefits of maintaining an engine designed for backward compatibility with one from the late 90s-early 2000s is that I have plenty of code to test against.

**Comment by fatcerberus** [comment]
Alright, I tested a bunch of different games, including the one that originally triggered the bug, and everything seems to be in working order now.

**Comment by fatcerberus** [comment]
What I still think is odd is the _way_ the bug manifests.  Knowing the cause, I'd expect the immediately preceding property (i.e. just before the getter) to be overwritten, but at least in my particular case, there were about 3 other properties in between.

**Comment by svaarala** [comment]
I added some bytecode examples to #1190 which explain why that happens. But to recap with a concrete example:

    { foo: 123, bar: 234 get quux() }

The correct bytecode sequence would be something like:

    NEWOBJ r1
    LDCONST r2, "foo"
    LDINT r3, 123  ; foo: 123
    LDCONST r4, "bar"
    LDINT r5, 234  ; bar: 234
    MPUTOBJ r1, r2, 4  ; set foo and bar plain properties
    LDCONST r2, "quux"
    CLOSURE r3, quux()  ; quux: getter quux()
    INITSET r1, r2
    ...

The bug was the the `LDCONST r2, "quux"` would go to the wrong register, say r6 here. Register r2 would then hold the old value, "foo" here.

So, INITSET would operate on "foo" and the quux() closure value, setting `.foo = quux`.

Depending on how many proprties are in the MPUTOBJ set, the older the incorrect getter key used would be.

**Pull request merged**
