### PR TITLE
Dispatch DUK_OP_ADD separately

### PR DESCRIPTION
**Pull request by svaarala**
Just a small tweak to opcode dispatch: addition is handled using a different helper than other binary arithmetic so dispatch it separately to eliminate an awkward comparison.

- [x] Change dispatch
- [ ] Add perf tests (fastint or not? now mixed)
- [ ] Releases entry

### CODE REVIEW

**Comment by fatcerberus** [comment]
Looking at the diff, it looks like it was done this way originally for footprint reasons?

**Comment by svaarala** [comment]
Yes, the trade-off is not very good however: ~50 bytes but it affects all dispatched arithmetic operations. There's not yet a "prefer footprint" vs. "prefer speed" in the executor so this is the better default here I think.

**Comment by svaarala** [comment]
The impact is quite small though - I've been prototyping a single level dispatch option (8 bit opcode) which may replace the current two level dispatch (6 bit main opcode field) so this pull may not matter if that gets merged later.

**Comment by svaarala** [comment]
Copied the test from this pull into #903; that seems promising for a later merge so I'll probably close this without merging in a bit, as the change here is irrelevant if #903 is merged.

**Comment by svaarala** [comment]
Closing as unmerged.

**Pull request closed without merging**
