### PR TITLE
Fix typo in examples/README.rst

### PR DESCRIPTION
**Pull request by luisbg**
Fixing a small typo. Unless the typo is a joke about bugs not being fixed 😄

### CODE REVIEW

**Comment by luisbg** [comment]
Bump. Sami, do you have time to merge this?

**Comment by svaarala** [comment]
Could you add yourself to the AUTHORS file (second list)?

**Comment by luisbg** [comment]
Sorry I had missed this. I've updated the PR with my name in the Authors.rst file.

**Comment by svaarala** [comment]
Thanks!

**Comment by luisbg** [comment]
Thank you for merging 😄

**Pull request merged**
