### PR TITLE
Add minimal console extra

### PR DESCRIPTION
**Pull request by svaarala**
Add a minimal (optional) console extra with:

- console.trace
- console.log (= console.debug)
- console.info
- console.warn
- console.error (= console.exception)
- console.assert
- console.dir

Object formatting is handled through `console.format` which uses JX by default, falling back to `ToString(v)` if JX serialization fails (e.g. due to a looped object). User code can easily replace `console.format` with something more appropriate.

Tasks:

- [x] Proxy semantics (required by specification to avoid errors on missing functions; not implemented like that by Node.js though)
- [x] Make Proxy semantics optional (init parameter)
- [x] Dense and multiline object formatting, maybe use multiline for console.dir() => Skip, Node.js also uses single line formatting
- [x] Dukweb console object
- [x] Add `DUK_CMDLINE_CONSOLE_SUPPORT` to enable console bindings for `duk`
- [x] Website: suggestion for I/O bindings (suggest where print/alert is mentioned)

These were marked as future work (XXX note in source):

- [x] Minimal level filtering
- [x] Compile time selection of stdout/stderr output, flushing behavior
- [x] Compare stdout/stderr behavior to Node (seems to use stderr for >= warn and trace, stdout for info and log)
- [x] Initialize using `duk_def_prop()`

### CODE REVIEW

**Comment by fatcerberus** [comment]
Speaking of JX serialization and loops, any progress on #331? ;)

**Comment by svaarala** [comment]
@fatcerberus Not so far, I'm still working through removing built-in bindings dependent on stdout/stderr or file I/O.

**Comment by fatcerberus** [comment]
That's an admirable pursuit, carry on. :)

**Comment by svaarala** [comment]
Overall I think a good order will be to first look at the multi property get/set API calls. If those turn out to be good enough, then `duk_def_prop()` could maybe use an object syntax (and avoid the variable value stack shape approach which would be inconsistent/asymmetric with a `duk_get_prop_desc()`). And finally, JX serialization could then take an object providing formatting arguments such as loop support etc. But we'll see :)

**Comment by fatcerberus** [comment]
Anyway this is nice, I'll keep this in mind for possible inclusion in minisphere 4.0.

**Comment by svaarala** [comment]
@fatcerberus I think most applications with an existing console model should just implement `console` on their own. The extra provided is an easy-to-use minimal implementation which can work as a starting point (and won't port to embedded platforms with non-standard I/O setups etc).

**Comment by svaarala** [comment]
Alright, this now looks something like this:

```
((o) Duktape [linenoise] 1.99.99 (v1.5.0-85-g9b70f20)

duk> console.assert(true, 'no error');
= undefined

duk> console.assert(1 > 2, 'should not happen', { foo: 123 });
AssertionError: should not happen {foo:123}
    at [anon] (dist/extras/console/duk_console.c:51) internal
    at assert () native strict preventsyield
    at global (input:1) preventsyield
= undefined

duk> console.log(1, 2, 3, { foo: 'bar', quux: [1,2,3] });
1 2 3 {foo:"bar",quux:[1,2,3]}
= undefined

duk> console.trace();
Trace
    at [anon] (dist/extras/console/duk_console.c:51) internal
    at trace () native strict preventsyield
    at global (input:1) preventsyield
= undefined
```

Formatting uses `String(v)` for everything but objects. For objects JX is attempted and if that fails (e.g. looped object), the formatter falls back to `String(v)`. This is a reasonable initial behavior IMO:

```
duk> var a = {}; var b = {}; a.ref = b;
= [object Object]

duk> console.log(a, b);
{ref:{}} {}
= undefined

duk> b.ref = a;  // complete loop
= [object Object]

duk> console.log(a, b);
[object Object] [object Object]
= undefined
```

User code can change the object formatting behavior simply by replacing `console.format`:

```
duk> console.log(123, {foo: 123});
123 {foo:123}
= undefined

duk> console.format = function format(v) { return '<OBJECT>'; };
= function format() {"ecmascript"}

duk> console.log(123, {foo: 123});
123 <OBJECT>
= undefined
```

**Comment by fatcerberus** [comment]
Like the JX formatting for objects.  Node.js does something similar in its REPL.

**Comment by svaarala** [comment]
A better solution would have some sanity limits on object key/value lengths (e.g. truncating strings and buffers above, say, 256 bytes/chars), detect loops (indicating them using some markup), handle accessors, etc. But maybe we'll leave these for future work :)

**Comment by svaarala** [comment]
The footprint of this extra is currently about 1.6kB on x64.

**Pull request merged**
