### PR TITLE
Add a pointer-not-pending-finalization assert to duk_push_heapptr()

### PR DESCRIPTION
**Pull request by svaarala**
Add a `duk_push_heapptr()` to catch cases where the application supplied pointer references an object already moved to the "pending finalization" mark-and-sweep list.

### CODE REVIEW

**Comment by svaarala** [comment]
@harold-b If you have a chance to test that this would have caught the issue in #914, it'd be nice to know :) I wrote this against v1.5.0 so it'd be easy for you to check. I'll then rebase this to master before merge.

**Comment by harold-b** [comment]
OK, will test it out in a little bit.

**Comment by harold-b** [comment]
Must DUK_DEBUG be set? (Just tested without it, no assertion was launched before the unreachable pointer was used)

**Comment by fatcerberus** [comment]
You need to enable `DUK_OPT_ASSERTIONS`.

**Comment by harold-b** [comment]
@fatcerberus Thank you, that did it :+1: 

The assert was indeed triggered.

**Comment by svaarala** [comment]
Good to know - I'll merge this to master to help other users :)

**Pull request merged**
