### PR TITLE
Fix the buildsite.py script to be python3 compatible

### PR DESCRIPTION
**Pull request by podsvirov**
Todo:
- [x] Fix the buildsite.py print calls to be python3 compatible
- [ ] Add to buildsite.py script python3 compatible md5 alternative
- [ ] Fix the buildsite.py script files read/write errors around python3's bytes type

### CODE REVIEW

**Comment by podsvirov** [comment]
@svaarala are there migration plans to python3 or the changes should be beat compatible with python2?

**Comment by svaarala** [comment]
All Python code will be removed and replaced with JS code. There is a replacement for the entire configure.py tooling for example and the Py files will first become wrappers to launch that (Py2+Py3 compatible) and then go away entirely.

In the meanwhile I intend to keep the Docker images working to run buildsite etc with Python2. While Python2 is going away, it will be fine for this kind of tooling (say site build) despite being out of maintenance.

**Comment by svaarala** [comment]
Example of configure.py conversion: https://github.com/svaarala/duktape/issues/1794#issuecomment-725479267

**Comment by podsvirov** [comment]
> All Python code will be removed and replaced with JS code. There is a replacement for the entire configure.py tooling for example and the Py files will first become wrappers to launch that (Py2+Py3 compatible) and then go away entirely.

Interesting initiative, especially part of the interpretation of the tooling scripts by the `ductape` itself.

> In the meanwhile I intend to keep the Docker images working to run buildsite etc with Python2. While Python2 is going away, it will be fine for this kind of tooling (say site build) despite being out of maintenance.

Does this mean that if these changes are compatible with python2, then the changes will be applied?

**Comment by svaarala** [comment]
I don't think it makes sense to support py2+py3 for the buildsite scripts (or any other Python code in the repo): it will create extra work in testing changes (hopefully few) with little benefit as py2 runs fine for site builds etc, especially since it's dockerized.

**Comment by podsvirov** [comment]
Okay, then I won't make an effort in that direction.

**Pull request closed without merging**
