### PR TITLE
Rework executor to use a single level dispatch

### PR DESCRIPTION
**Pull request by svaarala**
This is a work in progress (far from complete) for reworking the bytecode format and the executor for a single level dispatch:
- Opcode format uses 8 bits for opcode, A, B, C each. Larger opcode field eliminates the need for EXTRA opcodes and a second level dispatch.
- Reg/const arguments are handled by moving the reg/const flags from the previously 9-bit (1-bit reg/const flag + 8-bit index) B and C register slots into the opcode field; for example, `ADD` consumes four consecutive opcode slots for different reg/const combinations for B and C fields.
- The revised reg/const handling allows the executor to handle each reg/const combination separately because each of the four opcodes can be dispatched to a separate case clause for faster execution
- For footprint optimized builds the four opcodes can map to the same case clause which does the reg/const explicitly as before.

The potential speedup for arithmetic heavy code is around 10-20%. The mandelbrot test, for example, improves from around 4.6 seconds to 3.9 seconds with optimizations currently in place (not yet complete).

Footprint for a performance optimized build will increase significantly, around 20kB or more. This is because the reg/const cases can now map to separate case clauses which have a significant footprint especially when inlining helpers.

Footprint for a size optimized build will likely increase somewhat - at the moment around 1kB but hopefully that can be brought down a bit.

Tasks:
- [x] Change opcode format macros, defines, etc
- [x] Compiler changes for opcode format
- [x] Executor changes for opcode format
- [x] Executor direct reg/const dispatch variants
- [x] Fix obvious remaining compiler and executor bugs by going through opcodes
- [x] Downgrade logging
- [x] SETALEN duk_harray optimization
- [x] Go through all opcodes and their field assignments, check for improvements; in particular, previous EXTRA opcodes can now use the A field
- [x] Reorganize opcodes a bit, eliminate opcode variants when e.g. B is never a constant
- [x] Debugger support for new opcode format
- [x] Debugger opcode metadata
- [x] Testcase fixes
- [x] Run testcases manually with compact and optimized executor
- [x] Run shuffle torture manually
- [x] Test footprint impact on ARM (as an example of another architecture)
- [x] Releases entry
- [x] Follow up issues/pulls => #908

### CODE REVIEW

**Comment by svaarala** [comment]
Optimized a few more opcode reg/const decoding e.g. comparisons (still some ways to go) and looks quite promising:
- test-mandel.js runs in 3.3 seconds compared to 4.6 in master
- test-empty-loop runs in 1.7 seconds compared to 2.6 in master

These are dispatch heavy tests of course (mandel test does a lot of looping, arithmetic, and comparisons and empty loop is basically just decrement and compare). Dispatch performance doesn't affect all kinds of code equally of course, but it's still nice :)

**Comment by svaarala** [comment]
Still work in progress, but now the executor has variants for small footprint vs. better performance and the footprint optimized build is roughly the same size as before (on x64 +300 bytes, on x86 -300 bytes, on x32 -700 bytes, roughly). Some of the size optimizations applied could also be applied to master so it's not entirely a fair comparison. In any case it's possible to improve performance on master while reducing footprint slightly for footprint optimized builds.

**Comment by svaarala** [comment]
Interesting, managed to shave off another 5-10% off dispatch time by ensuring that (1) the switch argument is 8 bits, and (2) forcing the compiler to emit code for each case clause. This allows the compiler to use the 8 opcode bits directly for an indirect jump without a bounds check.

Unless one adds dummy clauses at least GCC -O2 will emit a bounds check before the indirect jump dispatch; cases failing the bound check jump to the default clause.

With this change `test-dev-mandel.js` runs in 3.0 seconds (3.3 before the change), 4.6 in master.

In practice I added case clauses for all unused opcodes, with a shared body containing essentially `int dummy_volatile = 0;` and "invalid opcode" handling. This ensures the clauses can't be joined with the default clause which could result in a bounds check again being emitted.

**Comment by svaarala** [comment]
Here are some performance results from gcc -O2:

- duk.O2.150json: build from 1.5.0, JSON fastpath enabled (it's also enabled in other comparison builds here)
- duk.O2.master: build from current master
- duk.O2.setalen: intermediate version built from this branch
- duk.O2: version built from this branch

The intermediate version is missing a few tweaks like:

- Opcode reordering
- Esuring that the opcode dispatch, which is based on an 8-bit value, avoids a bounds check
- Small odds and ends

<table>
<tr><th></th><th>duk.O2</th><th>duk.O2.setalen</th><th>duk.O2.master</th><th>duk.O2.150json</th></tr>
<tr><td>test-add-fastint.js</td><td>0.63</td><td>0.69</td><td>0.86</td><td>0.83</td></tr>
<tr><td>test-add-float.js</td><td>0.63</td><td>0.68</td><td>0.85</td><td>0.82</td></tr>
<tr><td>test-add-nan-fastint.js</td><td>0.73</td><td>0.77</td><td>0.92</td><td>0.95</td></tr>
<tr><td>test-add-nan.js</td><td>0.63</td><td>0.68</td><td>0.86</td><td>0.83</td></tr>
<tr><td>test-arith-add.js</td><td>2.53</td><td>2.73</td><td>3.45</td><td>3.31</td></tr>
<tr><td>test-arith-div.js</td><td>7.27</td><td>7.42</td><td>8.27</td><td>8.30</td></tr>
<tr><td>test-arith-mod.js</td><td>6.57</td><td>6.68</td><td>7.72</td><td>7.95</td></tr>
<tr><td>test-arith-mul.js</td><td>3.59</td><td>4.18</td><td>4.79</td><td>4.48</td></tr>
<tr><td>test-arith-sub.js</td><td>2.74</td><td>2.89</td><td>3.50</td><td>3.63</td></tr>
<tr><td>test-array-append.js</td><td>0.53</td><td>0.52</td><td>0.62</td><td>0.73</td></tr>
<tr><td>test-array-cons-list.js</td><td>0.93</td><td>0.94</td><td>0.93</td><td>2.32</td></tr>
<tr><td>test-array-foreach.js</td><td>2.71</td><td>2.68</td><td>2.87</td><td>2.81</td></tr>
<tr><td>test-array-literal.js</td><td>1.58</td><td>1.59</td><td>1.61</td><td>1.82</td></tr>
<tr><td>test-array-push.js</td><td>3.76</td><td>3.81</td><td>3.86</td><td>4.45</td></tr>
<tr><td>test-array-read-lenloop.js</td><td>2.26</td><td>2.27</td><td>2.72</td><td>2.65</td></tr>
<tr><td>test-array-read.js</td><td>1.78</td><td>1.79</td><td>2.19</td><td>2.16</td></tr>
<tr><td>test-array-write-length.js</td><td>1.86</td><td>1.91</td><td>2.16</td><td>2.89</td></tr>
<tr><td>test-array-write.js</td><td>1.71</td><td>1.74</td><td>1.84</td><td>2.70</td></tr>
<tr><td>test-assign-add.js</td><td>3.76</td><td>3.83</td><td>5.43</td><td>5.35</td></tr>
<tr><td>test-assign-addto-nan.js</td><td>1.20</td><td>1.28</td><td>1.49</td><td>1.58</td></tr>
<tr><td>test-assign-addto.js</td><td>3.72</td><td>3.79</td><td>5.44</td><td>5.29</td></tr>
<tr><td>test-assign-boolean.js</td><td>4.77</td><td>4.83</td><td>4.82</td><td>4.85</td></tr>
<tr><td>test-assign-const-int.js</td><td>2.44</td><td>2.52</td><td>2.58</td><td>2.60</td></tr>
<tr><td>test-assign-const-int2.js</td><td>4.89</td><td>6.01</td><td>9.13</td><td>9.08</td></tr>
<tr><td>test-assign-const.js</td><td>4.00</td><td>4.23</td><td>3.98</td><td>4.23</td></tr>
<tr><td>test-assign-literal.js</td><td>3.76</td><td>3.77</td><td>4.60</td><td>4.25</td></tr>
<tr><td>test-assign-proplhs-reg.js</td><td>3.49</td><td>3.68</td><td>3.60</td><td>3.75</td></tr>
<tr><td>test-assign-proprhs.js</td><td>3.74</td><td>3.89</td><td>4.03</td><td>4.18</td></tr>
<tr><td>test-assign-reg.js</td><td>2.77</td><td>2.80</td><td>2.86</td><td>2.81</td></tr>
<tr><td>test-base64-decode-whitespace.js</td><td>1.87</td><td>1.87</td><td>1.87</td><td>1.87</td></tr>
<tr><td>test-base64-decode.js</td><td>1.52</td><td>1.52</td><td>1.52</td><td>1.52</td></tr>
<tr><td>test-base64-encode.js</td><td>1.83</td><td>1.82</td><td>1.82</td><td>1.82</td></tr>
<tr><td>test-bitwise-ops.js</td><td>1.66</td><td>1.90</td><td>2.73</td><td>2.59</td></tr>
<tr><td>test-break-fast.js</td><td>1.35</td><td>1.48</td><td>1.85</td><td>1.60</td></tr>
<tr><td>test-break-slow.js</td><td>7.57</td><td>7.44</td><td>8.06</td><td>7.95</td></tr>
<tr><td>test-buffer-nodejs-read.js</td><td>2.24</td><td>2.21</td><td>2.76</td><td>2.61</td></tr>
<tr><td>test-buffer-nodejs-write.js</td><td>3.01</td><td>2.97</td><td>3.09</td><td>3.07</td></tr>
<tr><td>test-buffer-object-read.js</td><td>2.16</td><td>2.23</td><td>2.80</td><td>2.62</td></tr>
<tr><td>test-buffer-object-write.js</td><td>3.01</td><td>2.98</td><td>3.09</td><td>3.08</td></tr>
<tr><td>test-buffer-plain-read.js</td><td>1.76</td><td>1.80</td><td>2.27</td><td>2.24</td></tr>
<tr><td>test-buffer-plain-write.js</td><td>1.69</td><td>1.73</td><td>1.85</td><td>1.83</td></tr>
<tr><td>test-call-basic-1.js</td><td>7.80</td><td>7.80</td><td>8.07</td><td>9.21</td></tr>
<tr><td>test-call-basic-2.js</td><td>7.88</td><td>7.79</td><td>8.10</td><td>9.20</td></tr>
<tr><td>test-call-basic-3.js</td><td>13.32</td><td>13.47</td><td>13.78</td><td>14.88</td></tr>
<tr><td>test-call-basic-4.js</td><td>34.21</td><td>34.86</td><td>35.85</td><td>37.32</td></tr>
<tr><td>test-call-native.js</td><td>13.14</td><td>13.12</td><td>13.74</td><td>13.90</td></tr>
<tr><td>test-call-prop.js</td><td>4.74</td><td>4.84</td><td>5.06</td><td>5.73</td></tr>
<tr><td>test-call-reg-new.js</td><td>6.52</td><td>6.62</td><td>6.63</td><td>6.65</td></tr>
<tr><td>test-call-reg.js</td><td>3.01</td><td>3.01</td><td>3.08</td><td>3.57</td></tr>
<tr><td>test-call-var.js</td><td>8.33</td><td>8.42</td><td>8.31</td><td>8.55</td></tr>
<tr><td>test-compile-mandel-nofrac.js</td><td>11.23</td><td>11.24</td><td>11.23</td><td>13.30</td></tr>
<tr><td>test-compile-mandel.js</td><td>14.20</td><td>14.38</td><td>14.30</td><td>16.46</td></tr>
<tr><td>test-compile-short.js</td><td>7.11</td><td>7.12</td><td>7.08</td><td>9.97</td></tr>
<tr><td>test-continue-fast.js</td><td>1.73</td><td>1.96</td><td>2.41</td><td>2.15</td></tr>
<tr><td>test-continue-slow.js</td><td>7.78</td><td>7.85</td><td>8.64</td><td>8.42</td></tr>
<tr><td>test-empty-loop-slowpath.js</td><td>1.85</td><td>1.96</td><td>1.97</td><td>1.96</td></tr>
<tr><td>test-empty-loop.js</td><td>1.59</td><td>1.75</td><td>2.52</td><td>2.27</td></tr>
<tr><td>test-error-create.js</td><td>2.25</td><td>2.21</td><td>2.18</td><td>3.34</td></tr>
<tr><td>test-fib.js</td><td>7.22</td><td>7.39</td><td>7.55</td><td>7.95</td></tr>
<tr><td>test-global-lookup.js</td><td>9.52</td><td>10.38</td><td>10.37</td><td>10.42</td></tr>
<tr><td>test-hello-world.js</td><td>0.00</td><td>0.00</td><td>0.00</td><td>0.00</td></tr>
<tr><td>test-hex-decode.js</td><td>3.60</td><td>3.61</td><td>3.60</td><td>3.60</td></tr>
<tr><td>test-hex-encode.js</td><td>2.84</td><td>2.82</td><td>2.81</td><td>2.83</td></tr>
<tr><td>test-jc-serialize-indented.js</td><td>3.37</td><td>3.37</td><td>3.36</td><td>3.51</td></tr>
<tr><td>test-jc-serialize.js</td><td>2.21</td><td>2.19</td><td>2.20</td><td>2.41</td></tr>
<tr><td>test-json-parse-hex.js</td><td>3.36</td><td>3.36</td><td>3.40</td><td>3.40</td></tr>
<tr><td>test-json-parse-integer.js</td><td>4.06</td><td>4.05</td><td>4.01</td><td>4.08</td></tr>
<tr><td>test-json-parse-number.js</td><td>5.17</td><td>5.16</td><td>5.20</td><td>5.18</td></tr>
<tr><td>test-json-parse-string.js</td><td>5.48</td><td>5.48</td><td>6.14</td><td>5.73</td></tr>
<tr><td>test-json-serialize-fastpath-loop.js</td><td>3.56</td><td>3.62</td><td>3.61</td><td>3.56</td></tr>
<tr><td>test-json-serialize-forceslow.js</td><td>10.36</td><td>10.31</td><td>10.36</td><td>11.02</td></tr>
<tr><td>test-json-serialize-hex.js</td><td>1.46</td><td>1.46</td><td>1.47</td><td>1.47</td></tr>
<tr><td>test-json-serialize-indented-deep100.js</td><td>2.16</td><td>2.14</td><td>2.14</td><td>2.38</td></tr>
<tr><td>test-json-serialize-indented-deep25.js</td><td>3.20</td><td>3.28</td><td>3.19</td><td>3.28</td></tr>
<tr><td>test-json-serialize-indented-deep500.js</td><td>1.34</td><td>1.36</td><td>1.36</td><td>1.48</td></tr>
<tr><td>test-json-serialize-indented.js</td><td>5.93</td><td>6.04</td><td>5.92</td><td>6.29</td></tr>
<tr><td>test-json-serialize-jsonrpc-message.js</td><td>2.01</td><td>2.01</td><td>2.00</td><td>2.00</td></tr>
<tr><td>test-json-serialize-nofrac.js</td><td>0.62</td><td>0.60</td><td>0.61</td><td>0.68</td></tr>
<tr><td>test-json-serialize-slowpath-loop.js</td><td>5.22</td><td>5.28</td><td>5.16</td><td>5.94</td></tr>
<tr><td>test-json-serialize.js</td><td>6.11</td><td>6.12</td><td>6.08</td><td>6.18</td></tr>
<tr><td>test-json-string-bench.js</td><td>4.86</td><td>4.92</td><td>4.96</td><td>5.25</td></tr>
<tr><td>test-json-string-stringify.js</td><td>5.23</td><td>5.25</td><td>5.18</td><td>5.05</td></tr>
<tr><td>test-jx-serialize-bufobj-forceslow.js</td><td>4.85</td><td>4.89</td><td>4.77</td><td>5.07</td></tr>
<tr><td>test-jx-serialize-bufobj.js</td><td>1.09</td><td>1.06</td><td>1.04</td><td>1.13</td></tr>
<tr><td>test-jx-serialize-indented.js</td><td>3.33</td><td>3.37</td><td>3.35</td><td>3.45</td></tr>
<tr><td>test-jx-serialize.js</td><td>2.16</td><td>2.17</td><td>2.19</td><td>2.40</td></tr>
<tr><td>test-mandel.js</td><td>3.10</td><td>3.30</td><td>4.66</td><td>4.36</td></tr>
<tr><td>test-object-garbage.js</td><td>4.44</td><td>4.48</td><td>4.54</td><td>4.35</td></tr>
<tr><td>test-object-literal.js</td><td>2.52</td><td>2.52</td><td>2.47</td><td>2.54</td></tr>
<tr><td>test-prop-read-4.js</td><td>4.19</td><td>4.27</td><td>4.54</td><td>4.71</td></tr>
<tr><td>test-prop-read-8.js</td><td>4.44</td><td>4.52</td><td>4.67</td><td>4.94</td></tr>
<tr><td>test-prop-read.js</td><td>4.25</td><td>4.33</td><td>4.59</td><td>4.75</td></tr>
<tr><td>test-prop-write-1024.js</td><td>4.52</td><td>4.39</td><td>5.66</td><td>5.09</td></tr>
<tr><td>test-prop-write-16.js</td><td>4.42</td><td>4.63</td><td>4.43</td><td>4.56</td></tr>
<tr><td>test-prop-write-256.js</td><td>5.63</td><td>4.38</td><td>4.42</td><td>4.63</td></tr>
<tr><td>test-prop-write-32.js</td><td>4.87</td><td>5.64</td><td>5.06</td><td>4.71</td></tr>
<tr><td>test-prop-write-4.js</td><td>3.90</td><td>3.98</td><td>4.02</td><td>4.19</td></tr>
<tr><td>test-prop-write-48.js</td><td>4.41</td><td>5.65</td><td>5.27</td><td>5.10</td></tr>
<tr><td>test-prop-write-64.js</td><td>4.36</td><td>4.96</td><td>5.06</td><td>4.74</td></tr>
<tr><td>test-prop-write-8.js</td><td>4.08</td><td>4.21</td><td>4.15</td><td>4.30</td></tr>
<tr><td>test-prop-write.js</td><td>3.92</td><td>3.99</td><td>4.05</td><td>4.20</td></tr>
<tr><td>test-reg-readwrite-object.js</td><td>3.05</td><td>3.19</td><td>3.21</td><td>3.16</td></tr>
<tr><td>test-reg-readwrite-plain.js</td><td>2.01</td><td>2.04</td><td>2.04</td><td>2.03</td></tr>
<tr><td>test-regexp-case-insensitive.js</td><td>23.41</td><td>23.43</td><td>23.26</td><td>24.48</td></tr>
<tr><td>test-regexp-string-parse.js</td><td>9.58</td><td>9.59</td><td>9.62</td><td>9.70</td></tr>
<tr><td>test-string-array-concat.js</td><td>5.56</td><td>5.59</td><td>6.01</td><td>6.63</td></tr>
<tr><td>test-string-charlen-ascii.js</td><td>1.33</td><td>1.34</td><td>1.30</td><td>1.32</td></tr>
<tr><td>test-string-charlen-nonascii.js</td><td>2.82</td><td>2.83</td><td>2.80</td><td>2.81</td></tr>
<tr><td>test-string-compare.js</td><td>1.98</td><td>2.10</td><td>3.72</td><td>3.78</td></tr>
<tr><td>test-string-decodeuri.js</td><td>3.78</td><td>3.78</td><td>3.58</td><td>3.69</td></tr>
<tr><td>test-string-encodeuri.js</td><td>4.01</td><td>4.01</td><td>4.01</td><td>3.99</td></tr>
<tr><td>test-string-garbage.js</td><td>8.36</td><td>8.55</td><td>8.37</td><td>8.48</td></tr>
<tr><td>test-string-intern-grow-short.js</td><td>11.83</td><td>11.50</td><td>12.06</td><td>11.77</td></tr>
<tr><td>test-string-intern-grow-short2.js</td><td>4.72</td><td>4.74</td><td>4.86</td><td>4.98</td></tr>
<tr><td>test-string-intern-grow.js</td><td>20.47</td><td>20.55</td><td>20.44</td><td>19.82</td></tr>
<tr><td>test-string-intern-grow2.js</td><td>1.83</td><td>1.87</td><td>1.81</td><td>1.75</td></tr>
<tr><td>test-string-intern-match-short.js</td><td>2.61</td><td>2.64</td><td>2.62</td><td>2.52</td></tr>
<tr><td>test-string-intern-match.js</td><td>0.23</td><td>0.23</td><td>0.23</td><td>0.26</td></tr>
<tr><td>test-string-intern-miss-short.js</td><td>2.98</td><td>3.04</td><td>3.01</td><td>3.25</td></tr>
<tr><td>test-string-intern-miss.js</td><td>1.14</td><td>1.13</td><td>1.15</td><td>1.18</td></tr>
<tr><td>test-string-plain-concat.js</td><td>1.00</td><td>1.05</td><td>1.05</td><td>1.04</td></tr>
<tr><td>test-string-uppercase.js</td><td>2.21</td><td>2.18</td><td>2.20</td><td>2.19</td></tr>
<tr><td>test-try-catch-nothrow.js</td><td>2.53</td><td>2.60</td><td>2.92</td><td>2.93</td></tr>
<tr><td>test-try-catch-throw.js</td><td>40.41</td><td>38.72</td><td>38.69</td><td>38.84</td></tr>
<tr><td>test-try-finally-nothrow.js</td><td>3.24</td><td>3.33</td><td>3.75</td><td>3.68</td></tr>
<tr><td>test-try-finally-throw.js</td><td>49.14</td><td>48.62</td><td>49.12</td><td>49.48</td></tr>
</table>

**Comment by fatcerberus** [comment]
Looks like a nice meaningful improvement (in microbenchmarks at least ;-)

I notice master is actually slower than 1.5.0 in a lot of tests.  Any idea why that is?

**Comment by svaarala** [comment]
Not sure - there are quite many small diffs which may have an impact so it's quite hard to tell. There's nothing obvious that should have an impact, but it's also not rare for there to be <5% differences simply due to the compiler using different code layout, or making different inlining decisions, etc.

**Comment by fatcerberus** [comment]
That's true, optimizing compilers are fickle beasts aren't they?

**Comment by svaarala** [comment]
Yup, there's a lot of noise in measuring improvements. There's also no automatic regression tests yet for different compilers or compiler options. That will be needed at some point to make it easier to spot intended and unintended effects of changes, but I'll need dedicated physical hardware for that in practice :)

Callgrind is potentially useful because it's not affected by real time:

```
duktape@keppihevonen:~/duktape$ valgrind --tool=callgrind ./duk.O2.150json tests/perf/test-empty-loop.js
==6076== Callgrind, a call-graph generating cache profiler
==6076== Copyright (C) 2002-2013, and GNU GPL'd, by Josef Weidendorfer et al.
==6076== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==6076== Command: ./duk.O2.150json tests/perf/test-empty-loop.js
==6076== 
==6076== For interactive control, run 'callgrind_control -h'.
==6076== 
==6076== Events    : Ir
==6076== Collected : 24703492299
==6076== 
==6076== I   refs:      24,703,492,299
duktape@keppihevonen:~/duktape$ valgrind --tool=callgrind ./duk.O2 tests/perf/test-empty-loop.js
==6095== Callgrind, a call-graph generating cache profiler
==6095== Copyright (C) 2002-2013, and GNU GPL'd, by Josef Weidendorfer et al.
==6095== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==6095== Command: ./duk.O2 tests/perf/test-empty-loop.js
==6095== 
==6095== For interactive control, run 'callgrind_control -h'.
==6095== 
==6095== Events    : Ir
==6095== Collected : 16204925476
==6095== 
==6095== I   refs:      16,204,925,476
```

Instruction count improvement is 35%; real time execution improvement based on `time` is roughly 27%, so they do correlate somewhat.

I'll probably add some callgrind tests to the regression set first.

**Comment by svaarala** [comment]
@fatcerberus Is there something in Minisphere that could be used to see if the dispatch performance matters there?

**Comment by svaarala** [comment]
Google benchmark changes:

```
duktape@keppihevonen:~/duktape/tests/google-v8-benchmark-v7$ sudo nice -20 ../../duk.O2.150json combined.js
PROGRESS Richards
RESULT Richards 122
PROGRESS DeltaBlue
RESULT DeltaBlue 136
PROGRESS Encrypt
PROGRESS Decrypt
RESULT Crypto 197
PROGRESS RayTrace
RESULT RayTrace 235
PROGRESS Earley
PROGRESS Boyer
RESULT EarleyBoyer 304
PROGRESS RegExp
RESULT RegExp 73.5
PROGRESS Splay
RESULT Splay 587
PROGRESS NavierStokes
RESULT NavierStokes 346
SCORE 208

duktape@keppihevonen:~/duktape/tests/google-v8-benchmark-v7$ sudo nice -20 ../../duk.O2.master combined.js
PROGRESS Richards
RESULT Richards 133
PROGRESS DeltaBlue
RESULT DeltaBlue 155
PROGRESS Encrypt
PROGRESS Decrypt
RESULT Crypto 181
PROGRESS RayTrace
RESULT RayTrace 201
PROGRESS Earley
PROGRESS Boyer
RESULT EarleyBoyer 311
PROGRESS RegExp
RESULT RegExp 92.3
PROGRESS Splay
RESULT Splay 577
PROGRESS NavierStokes
RESULT NavierStokes 536
SCORE 225

duktape@keppihevonen:~/duktape/tests/google-v8-benchmark-v7$ sudo nice -20 ../../duk.O2 combined.js
PROGRESS Richards
RESULT Richards 147
PROGRESS DeltaBlue
RESULT DeltaBlue 170
PROGRESS Encrypt
PROGRESS Decrypt
RESULT Crypto 206
PROGRESS RayTrace
RESULT RayTrace 239
PROGRESS Earley
PROGRESS Boyer
RESULT EarleyBoyer 320
PROGRESS RegExp
RESULT RegExp 92.1
PROGRESS Splay
RESULT Splay 648
PROGRESS NavierStokes
RESULT NavierStokes 604
SCORE 248
```

Again, this is pretty rough because I'm running on a laptop with thermal throttling (and I'm too lazy to reconfigure cpufreq right now ;). But in short, the overall score since 1.5.0 has improved a bit:

- 1.5.0: 208
- master: 225
- this branch: 248

The relevance of e.g. raytracing to embedded scripting is another question :-)

**Comment by svaarala** [comment]
This is close to merge ready now. I'll fix a few odds and ends, improve testcase coverage a bit, and do a read-through of the diff. There's considerable risk of some minor fallout (not caught by existing tests) as there a lot of small changes in the compiler and the executor, so it's good to have this in master way before a potential 2.0 release.

**Comment by fatcerberus** [comment]
@svaarala Thermal throttling sucks.  I used to see that a lot on my old i7 laptop, the CPU would regularly hit 100C and throttle under heavy load.  Not nice when I was using it to encode video. :-\

Anyway, minisphere up to v3.3 historically hasn't been very dispatch sensitive because the Sphere v1 API was designed so that the engine did most of the heavy lifting.  That will likely change now that minisphere 4.x is out, though: Sphere v2 API provides only low-level primitives in the core and most of the mid-level infrastructure is written in JS--including, eventually, a map engine.  So dispatch performance will matter much more going forward.

I'll see if I can come up with a performance test based on real-world usage in my spare time.

**Comment by svaarala** [comment]
Right, that's one of the main intended use cases for Duktape: orchestrating sequences of native calls. There are other use cases of course, some property heavy, others call heavy (small callbacks called very often), etc.

**Pull request merged**
