### PR TITLE
Move executor setjmp catchpoint to an outer wrapper function

### PR DESCRIPTION
**Pull request by svaarala**
Split executor into an outer and an inner function. The outer function contains the setjmp catchpoint and longjmp handling. The inner function is free of setjmp and longjmp catching. In quick tests this improves dispatch performance (empty loop test) by ~5% for native code and ~25% for Emscripten. The split is also useful for adding C++ exception support as a replacement for setjmp/longjmp because the outer function is small and its control flow is easier to tweak.

- [x] Implement the basic split
- [x] Recheck volatiles, maybe can reduce some of them now => no volatiles left!
- [x] Recheck comments in the executor
- [x] Check if `fun` local is useful (or if it's better to re-lookup through `thr`)
- [x] Figure out why `tests/perf/test-assign-addto.js` is much slower on x86 (than x64) if initial `t` is uninitialized and ends up as a NaN, perhaps NaN normalization check is the reason?
- [x] Stress testing
- [x] Code issues note: setjmp should be confined to a wrapper for performance and to allow easier setjmp/longjmp replacement
- [x] Releases entry

This will be merged after #348.

### CODE REVIEW

**Comment by svaarala** [comment]
Quick test on having a `fun` local or not having a `fun` local in the inner bytecode executor (where every little bit of difference matters).

Size on x64:

```
$ size duk.fun duk.nofun
   text	   data	    bss	    dec	    hex	filename
 253542	   1336	     40	 254918	  3e3c6	duk.fun
 253622	   1336	     40	 254998	  3e416	duk.nofun

$ size duk.O2.fun duk.O2.nofun
   text	   data	    bss	    dec	    hex	filename
 312789	   1384	     40	 314213	  4cb65	duk.O2.fun
 312789	   1384	     40	 314213	  4cb65	duk.O2.nofun
```

For x86 (where register pressure matters more):

```
$ size duk.x86_*
   text	   data	    bss	    dec	    hex	filename
 255382	    704	     48	 256134	  3e886	duk.x86_fun
 255414	    704	     48	 256166	  3e8a6	duk.x86_nofun

$ size duk.O2.x86_*
   text	   data	    bss	    dec	    hex	filename
 308406	    772	     48	 309226	  4b7ea	duk.O2.x86_fun
 308438	    772	     48	 309258	  4b80a	duk.O2.x86_nofun
```

Size differences are pretty marginal. Performance seems to be slightly better without `fun` in the stack frame (I'll run a full test tonight) on x64 at least.

**Comment by svaarala** [comment]
Arithmetic on x86 involving a NaN is ~10x slower than when other IEEE doubles are worked with. This rough difference happens even without packed `duk_tval` so it's apparently not related to NaN normalizatin involved with packing (as I first thought).

Here's an example:

```
test-add-fastint.js           : duk.O2.fun  0.09 duk.O2.x86_fun  0.14
test-add-float.js             : duk.O2.fun  0.09 duk.O2.x86_fun  0.24
test-add-nan-fastint.js       : duk.O2.fun  0.09 duk.O2.x86_fun  1.51
test-add-nan.js               : duk.O2.fun  0.09 duk.O2.x86_fun  1.51
```

This is more of a curiosity than an actual issue: ordinary code doesn't deal with NaNs very much.

**Comment by fatcerberus** [comment]
Even less so because ES only has a single NaN value so its practical usage is basically limited to use as an error flag.  If your calculation ends up with a NaN in it it'll poison the whole thing, so performance doesn't really matter at the point IMO.

**Comment by fatcerberus** [comment]
For the sake of argument though, since you brought it up... Does it make a difference if the NaNs involved are signaling vs. quiet?

**Comment by svaarala** [comment]
Ecmascript actually doesn't say you only have one NaN value, but rather that an implementation is allowed to substitute one NaN for another.

For unpacked `duk_tval` Duktape uses whatever NaNs the platform uses; if you pass in two different NaNs through `duk_push_number()` they'll go through as is and usually maintain their specific NaN bits along the way.

For packed `duk_tval` Duktape initializes a few of the high bits (to ensure the value is a specific kind of NaN and doesn't interfere with other tagged types) but low bits are not set so there's a "family" of NaNs used in this case. In practice the low bits are set to zero by the platform so that the NaN that comes out has a single form.

Usually this matters very little, but you can see the difference when you write NaN values through a `DataView`, for example:

```
# For x86 packed duk_tval
((o) Duktape [no readline] 1.3.99 (v1.3.0-87-g8af8c0f-dirty)
duk> d = new DataView(new Uint8Array(8)); d.setFloat64(0, 0/0); print(Duktape.enc('jx', d));
|7ff8000000000000|
= undefined

# For x64 unpacked duk_tval
((o) Duktape 1.3.99 (v1.3.0-87-g8af8c0f-dirty)
duk> d = new DataView(new Uint8Array(8)); d.setFloat64(0, 0/0); print(Duktape.enc('jx', d));
|fff8000000000000|
= undefined
```

If user code pushes a specific NaN it should retain its specific bits when written through a DataView as above with unpacked `duk_tval`.

**Comment by svaarala** [comment]
All NaNs involved should be quiet (highest mantissa bit set). Duktape's normalized NaN format is `7ff8....` which should also be a quiet NaN.

**Comment by svaarala** [comment]
Anyway, I'll add a few perf test cases to demonstrate the difference, but it doesn't really matter all that much.

**Comment by fatcerberus** [comment]
Just chalk it up to the silicon circuits not really being optimized for it. :)

**Comment by svaarala** [comment]
The x86 version uses x87 while x64 uses SSE, which may also be somehow related.

**Comment by svaarala** [comment]
It seems x64 is perhaps a bit faster without a `fun` local, while x86 is the opposite. So I guess I'll just use a performance macro for that with default without `fun` in case it matters more on some other platforms.

```
test-add-fastint.js           : duk.O2.x64_fun  0.08 duk.O2.x64_nofun  0.07 duk.O2.x86_fun  0.12 duk.O2.x86_nofun  0.12 duk.O2.130   n/a rhino  0.32 python   n/a
test-add-float.js             : duk.O2.x64_fun  0.08 duk.O2.x64_nofun  0.07 duk.O2.x86_fun  0.22 duk.O2.x86_nofun  0.22 duk.O2.130   n/a rhino  0.29 python   n/a
test-add-nan-fastint.js       : duk.O2.x64_fun  0.09 duk.O2.x64_nofun  0.09 duk.O2.x86_fun  1.38 duk.O2.x86_nofun  1.38 duk.O2.130   n/a rhino  0.29 python   n/a
test-add-nan.js               : duk.O2.x64_fun  0.08 duk.O2.x64_nofun  0.08 duk.O2.x86_fun  1.34 duk.O2.x86_nofun  1.35 duk.O2.130   n/a rhino  0.30 python   n/a
test-array-read.js            : duk.O2.x64_fun  1.84 duk.O2.x64_nofun  1.81 duk.O2.x86_fun  2.36 duk.O2.x86_nofun  2.32 duk.O2.130   n/a rhino  0.65 python  1.72
test-array-write.js           : duk.O2.x64_fun  2.58 duk.O2.x64_nofun  2.56 duk.O2.x86_fun  3.48 duk.O2.x86_nofun  3.54 duk.O2.130   n/a rhino  1.19 python  2.41
test-assign-add.js            : duk.O2.x64_fun  4.93 duk.O2.x64_nofun  4.60 duk.O2.x86_fun  8.85 duk.O2.x86_nofun  8.82 duk.O2.130   n/a rhino  3.69 python 13.69
test-assign-addto-nan.js      : duk.O2.x64_fun  1.45 duk.O2.x64_nofun  1.44 duk.O2.x86_fun 27.14 duk.O2.x86_nofun 27.32 duk.O2.130  2.06 rhino  0.50 python   n/a
test-assign-addto.js          : duk.O2.x64_fun  5.06 duk.O2.x64_nofun  5.13 duk.O2.x86_fun  9.84 duk.O2.x86_nofun  9.90 duk.O2.130  9.50 rhino  4.42 python 18.24
test-assign-const-int.js      : duk.O2.x64_fun  2.70 duk.O2.x64_nofun  2.66 duk.O2.x86_fun  3.88 duk.O2.x86_nofun  3.80 duk.O2.130  7.39 rhino  0.37 python  5.89
test-assign-const.js          : duk.O2.x64_fun  4.16 duk.O2.x64_nofun  3.98 duk.O2.x86_fun  4.89 duk.O2.x86_nofun  4.85 duk.O2.130  6.54 rhino  0.35 python  5.95
test-assign-literal.js        : duk.O2.x64_fun  4.90 duk.O2.x64_nofun  4.86 duk.O2.x86_fun  4.94 duk.O2.x86_nofun  5.09 duk.O2.130  7.48 rhino  0.35 python 13.56
test-assign-reg.js            : duk.O2.x64_fun  3.11 duk.O2.x64_nofun  3.07 duk.O2.x86_fun  4.07 duk.O2.x86_nofun  4.43 duk.O2.130  3.07 rhino  0.37 python  6.25
test-bitwise-ops.js           : duk.O2.x64_fun  0.82 duk.O2.x64_nofun  0.78 duk.O2.x86_fun  0.87 duk.O2.x86_nofun  0.88 duk.O2.130  0.94 rhino  8.98 python   n/a
test-break-fast.js            : duk.O2.x64_fun  1.80 duk.O2.x64_nofun  1.67 duk.O2.x86_fun  1.71 duk.O2.x86_nofun  1.67 duk.O2.130  1.55 rhino  0.34 python   n/a
test-break-slow.js            : duk.O2.x64_fun  8.54 duk.O2.x64_nofun  8.05 duk.O2.x86_fun  9.91 duk.O2.x86_nofun  9.87 duk.O2.130 11.25 rhino  0.32 python   n/a
test-buffer-nodejs-read.js    : duk.O2.x64_fun  2.45 duk.O2.x64_nofun  2.38 duk.O2.x86_fun  3.24 duk.O2.x86_nofun  3.19 duk.O2.130  2.42 rhino   n/a python   n/a
test-buffer-nodejs-write.js   : duk.O2.x64_fun  3.32 duk.O2.x64_nofun  3.34 duk.O2.x86_fun  3.91 duk.O2.x86_nofun  3.94 duk.O2.130  3.30 rhino   n/a python   n/a
test-buffer-object-read.js    : duk.O2.x64_fun  2.45 duk.O2.x64_nofun  2.38 duk.O2.x86_fun  3.17 duk.O2.x86_nofun  3.17 duk.O2.130  2.42 rhino   n/a python   n/a
test-buffer-object-write.js   : duk.O2.x64_fun  3.31 duk.O2.x64_nofun  3.34 duk.O2.x86_fun  3.92 duk.O2.x86_nofun  3.94 duk.O2.130  3.30 rhino   n/a python   n/a
test-buffer-plain-read.js     : duk.O2.x64_fun  2.11 duk.O2.x64_nofun  2.07 duk.O2.x86_fun  2.46 duk.O2.x86_nofun  2.41 duk.O2.130  2.00 rhino   n/a python   n/a
test-buffer-plain-write.js    : duk.O2.x64_fun  1.83 duk.O2.x64_nofun  1.83 duk.O2.x86_fun  2.25 duk.O2.x86_nofun  2.29 duk.O2.130  1.74 rhino   n/a python   n/a
test-call-basic.js            : duk.O2.x64_fun  9.88 duk.O2.x64_nofun  9.85 duk.O2.x86_fun 11.86 duk.O2.x86_nofun 11.86 duk.O2.130 12.13 rhino  1.44 python  5.23
test-call-native.js           : duk.O2.x64_fun 15.95 duk.O2.x64_nofun 15.70 duk.O2.x86_fun 17.33 duk.O2.x86_nofun 17.48 duk.O2.130 18.87 rhino  1.49 python   n/a
test-compile-mandel-nofrac.js : duk.O2.x64_fun 13.75 duk.O2.x64_nofun 13.77 duk.O2.x86_fun 15.22 duk.O2.x86_nofun 15.50 duk.O2.130 13.35 rhino  7.60 python   n/a
test-compile-mandel.js        : duk.O2.x64_fun 16.65 duk.O2.x64_nofun 16.69 duk.O2.x86_fun 19.64 duk.O2.x86_nofun 19.63 duk.O2.130 16.41 rhino  7.63 python   n/a
test-compile-short.js         : duk.O2.x64_fun 10.16 duk.O2.x64_nofun 10.16 duk.O2.x86_fun 11.28 duk.O2.x86_nofun 11.36 duk.O2.130 10.16 rhino  4.11 python   n/a
test-continue-fast.js         : duk.O2.x64_fun  2.12 duk.O2.x64_nofun  1.98 duk.O2.x86_fun  2.15 duk.O2.x86_nofun  2.16 duk.O2.130  1.91 rhino  2.26 python   n/a
test-continue-slow.js         : duk.O2.x64_fun  8.24 duk.O2.x64_nofun  8.13 duk.O2.x86_fun 10.53 duk.O2.x86_nofun 10.55 duk.O2.130 11.79 rhino  2.26 python   n/a
test-empty-loop.js            : duk.O2.x64_fun  2.53 duk.O2.x64_nofun  2.40 duk.O2.x86_fun  3.20 duk.O2.x86_nofun  3.20 duk.O2.130  2.34 rhino  0.67 python  4.52
test-fib.js                   : duk.O2.x64_fun  8.12 duk.O2.x64_nofun  8.26 duk.O2.x86_fun  9.31 duk.O2.x86_nofun  9.35 duk.O2.130  8.57 rhino  1.25 python  2.42
test-global-lookup.js         : duk.O2.x64_fun 10.85 duk.O2.x64_nofun 11.51 duk.O2.x86_fun 13.06 duk.O2.x86_nofun 13.37 duk.O2.130 10.00 rhino  1.24 python   n/a
test-hello-world.js           : duk.O2.x64_fun  0.00 duk.O2.x64_nofun  0.00 duk.O2.x86_fun  0.00 duk.O2.x86_nofun  0.00 duk.O2.130  0.00 rhino  0.24 python  0.00
test-hex-decode.js            : duk.O2.x64_fun  5.33 duk.O2.x64_nofun  5.33 duk.O2.x86_fun  5.40 duk.O2.x86_nofun  5.43 duk.O2.130  5.34 rhino   n/a python 12.50
test-hex-encode.js            : duk.O2.x64_fun 26.64 duk.O2.x64_nofun 26.58 duk.O2.x86_fun 25.48 duk.O2.x86_nofun 25.47 duk.O2.130 26.84 rhino   n/a python  2.88
test-json-integer-parse.js    : duk.O2.x64_fun  0.40 duk.O2.x64_nofun  0.41 duk.O2.x86_fun  0.47 duk.O2.x86_nofun  0.47 duk.O2.130  0.42 rhino  1.07 python  0.07
test-json-number-parse.js     : duk.O2.x64_fun  5.05 duk.O2.x64_nofun  5.06 duk.O2.x86_fun  7.49 duk.O2.x86_nofun  7.47 duk.O2.130  5.12 rhino  1.59 python  0.29
test-json-serialize.js        : duk.O2.x64_fun  1.56 duk.O2.x64_nofun  1.55 duk.O2.x86_fun  2.54 duk.O2.x86_nofun  2.53 duk.O2.130  1.56 rhino  3.33 python  0.51
test-json-string-bench.js     : duk.O2.x64_fun  5.59 duk.O2.x64_nofun  5.55 duk.O2.x86_fun  7.03 duk.O2.x86_nofun  7.10 duk.O2.130  5.45 rhino  2.12 python   n/a
test-json-string-parse.js     : duk.O2.x64_fun  0.47 duk.O2.x64_nofun  0.49 duk.O2.x86_fun  0.56 duk.O2.x86_nofun  0.55 duk.O2.130  0.56 rhino  2.47 python   n/a
test-json-string-stringify.js : duk.O2.x64_fun  1.33 duk.O2.x64_nofun  1.34 duk.O2.x86_fun  1.25 duk.O2.x86_nofun  1.24 duk.O2.130  1.28 rhino  6.18 python  0.48
test-mandel.js                : duk.O2.x64_fun  4.54 duk.O2.x64_nofun  4.30 duk.O2.x86_fun  8.68 duk.O2.x86_nofun  8.69 duk.O2.130  4.70 rhino  1.63 python   n/a
test-prop-read.js             : duk.O2.x64_fun  5.30 duk.O2.x64_nofun  5.14 duk.O2.x86_fun  6.15 duk.O2.x86_nofun  6.18 duk.O2.130  5.22 rhino  0.69 python  2.36
test-prop-write.js            : duk.O2.x64_fun  4.63 duk.O2.x64_nofun  4.42 duk.O2.x86_fun  5.52 duk.O2.x86_nofun  5.76 duk.O2.130  4.44 rhino  1.81 python  2.48
test-reg-readwrite-object.js  : duk.O2.x64_fun  3.02 duk.O2.x64_nofun  3.00 duk.O2.x86_fun  3.99 duk.O2.x86_nofun  4.07 duk.O2.130  3.74 rhino  0.37 python  4.73
test-reg-readwrite-plain.js   : duk.O2.x64_fun  2.04 duk.O2.x64_nofun  2.08 duk.O2.x86_fun  2.74 duk.O2.x86_nofun  2.85 duk.O2.130  2.50 rhino  0.38 python  4.75
test-regexp-string-parse.js   : duk.O2.x64_fun 11.09 duk.O2.x64_nofun 11.01 duk.O2.x86_fun 13.43 duk.O2.x86_nofun 13.46 duk.O2.130 10.49 rhino   n/a python  0.46
test-string-array-concat.js   : duk.O2.x64_fun  6.90 duk.O2.x64_nofun  6.81 duk.O2.x86_fun  8.02 duk.O2.x86_nofun  8.12 duk.O2.130  6.41 rhino  2.02 python  2.83
test-string-compare.js        : duk.O2.x64_fun  4.16 duk.O2.x64_nofun  3.96 duk.O2.x86_fun  5.01 duk.O2.x86_nofun  5.07 duk.O2.130  3.79 rhino  5.74 python  4.90
test-string-decodeuri.js      : duk.O2.x64_fun  3.70 duk.O2.x64_nofun  3.70 duk.O2.x86_fun  5.15 duk.O2.x86_nofun  5.14 duk.O2.130  3.55 rhino  1.92 python   n/a
test-string-encodeuri.js      : duk.O2.x64_fun  4.36 duk.O2.x64_nofun  4.35 duk.O2.x86_fun  5.50 duk.O2.x86_nofun  5.50 duk.O2.130  4.35 rhino  6.85 python   n/a
test-string-intern-match.js   : duk.O2.x64_fun  2.37 duk.O2.x64_nofun  2.37 duk.O2.x86_fun  2.40 duk.O2.x86_nofun  2.40 duk.O2.130  2.37 rhino   n/a python   n/a
test-string-intern-miss.js    : duk.O2.x64_fun  2.54 duk.O2.x64_nofun  2.54 duk.O2.x86_fun  2.58 duk.O2.x86_nofun  2.61 duk.O2.130  2.51 rhino   n/a python   n/a
test-string-plain-concat.js   : duk.O2.x64_fun  4.09 duk.O2.x64_nofun  4.06 duk.O2.x86_fun  4.03 duk.O2.x86_nofun  4.01 duk.O2.130  4.09 rhino  0.31 python  0.01
test-string-uppercase.js      : duk.O2.x64_fun  2.56 duk.O2.x64_nofun  2.57 duk.O2.x86_fun  2.97 duk.O2.x86_nofun  3.02 duk.O2.130  2.58 rhino  2.56 python  1.19
```

**Comment by fatcerberus** [comment]
Huh.  I wonder if x86 is slower due to increased register pressure?  Just for kicks, what happens if you make `fun` volatile (preventing it from being bound to a register)?

**Comment by svaarala** [comment]
I tried volatiles before and for the most part they either have no effect or reduce performance slightly. Most likely this is caused by the volatile value being read multiple times if an expression e.g. involves both a flag check and a value read.

To use volatiles to ensure the value is not register allocated is perhaps not very clean - but one would need to do something like this for it to work well:

```
volatile duk_hcompiledfunction *fun_volatile;

...

{
    duk_hcompiledfunction *fun_tmp = (duk_hcompiledfunction *) fun_volatile;
    /* work with 'fun_tmp' only locally and then forget it. */
}
```

This avoids multiple volatile lookups. But even with changes like this the differences are minimal, so I suspect the variables are already spilled (and not register allocated) and caching plays more of a role.

**Pull request merged**
